### ISSUE TITLE
Fix Run Command

### ISSUE THREAD

**Issue by mike-lloyd03** [cryinkfly/Fusion-360---Linux-Wine-Version-#1]
Thanks for putting this together. Can you fix this line? There's a lot of extra spaces and it's unclear what should be in quotation marks and what shouldn't. Using a codeblock for the actual command that should be entered into the terminal should help clear this up.

```
Run Fusion 360: "env WINEPREFIX =" / home / steve / .wine "wine C: \ windows \ command \ start.exe / Unix /home/YOUR-USER-NAME/.wine/dosdevices/c: / ProgramData / Microsoft / Windows / Start \ Menu / Programs / Autodesk / Autodesk \ Fusion \ 360.lnk "
```

**Comment by cryinkfly** [comment]
Ok. Thank You very much for this information. :-)
