### ISSUE TITLE
Drawing won't start *solved*

### ISSUE THREAD

**Issue by midtbo** [cryinkfly/Fusion-360---Linux-Wine-Version-#108]
Hi,
Just want to start with the fact that this is what i need to be able to get rid of windows on my computer!
I do really apreciate the work you guys do here.

So my problem is that i cant get drawing to start. 
![image](https://user-images.githubusercontent.com/16806739/135418493-6b8150cf-a57a-4e69-9645-32b6cc9dc974.png)

I have tried to look through everyting in the RAEDME searched all the issues and everything, but i cant seem to find anything like this error. When i close the window, i get this message:
![image](https://user-images.githubusercontent.com/16806739/135418758-1848b4e8-7034-4235-8362-75e4761557bf.png)

when i go out of that window, I can see that it has kind of loaded the drawing section with the buttons etc at top, but goes back into design again.

Running: 
Debian11
wine-6.18 (staging)
Nvidia proprietary driver (470.74)
RTX2070

Again thank you very much for the work!

**Comment by cryinkfly** [comment]
Hey 👋🏻, wir you have installed the standard installation of Autodesk Fusion 360?

**Comment by midtbo** [comment]
I have installed the standard version, without any adons.
Not sure which launcher i did start. The video in your link seems to be removed.

**Comment by cryinkfly** [comment]
Can you run this command:

    env WINEPREFIX="/$HOME/.wineprefixes/fusion360" wine C:\\windows\\command\\start.exe /Unix /$HOME/.wineprefixes/fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk

**Comment by midtbo** [comment]
That worked!!!
![image](https://user-images.githubusercontent.com/16806739/135493284-504ff639-1b36-4dbc-b6c1-ccf8a4771c50.png)

How do i get this into the .desktop shortcut?

**Comment by cryinkfly** [comment]
https://user-images.githubusercontent.com/79079633/135494610-0b0b37a4-1ddc-4121-b5cf-65d300f8f357.mov
