### ISSUE TITLE
Can't open Fusion 360 after normal install. - External Drive *solved*

### ISSUE THREAD

**Issue by vasiaplaton** [cryinkfly/Fusion-360---Linux-Wine-Version-#111]
Hello. I'm install fusion360 by your script in another folder(in this case in /media/vasia/HDD1TB/Fusion360/), and installing done without errors. After installing, I'm clicking on icon in menu, and nothing happen. Next, I'm open .desktop command file and open paste command in Exec= in terminal. When started  from terminal it open small Wine window with text "File not found". Here's terminal output

`
vasia@vasia-pc:/media/vasia/HDD1TB/Fusion360$ env WINEPREFIX="/media/vasia/HDD1TB/Fusion360/" /opt/wine-staging/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix /media/vasia/HDD1TB/Fusion360/dosdevices/c:/users/Public/Desktop/Autodesk\\ Fusion\\ 360.lnk

002c:fixme:winediag:LdrInitializeThunk wine-staging 6.18 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0068:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0078:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0078:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00a0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
00a0:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
002c:fixme:ver:GetCurrentPackageId (000000000067FD70 0000000000000000): stub
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0100:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0100:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
0108:fixme:exec:SHELL_execute flags ignored: 0x00000100
0108:err:exec:SHELL_ExecuteW cannot set directory L"C:\\users\\Public\\Desktop\\Autodesk"
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Invalid window handle.

0100:fixme:ver:GetCurrentPackageId (00000000006AFD70 0000000000000000): stub

`

**Comment by cryinkfly** [comment]
Can you open a terminal and run this command:

    $(find /media/vasia/HDD1TB/Fusion360 -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.wineprefixes/fusion360" wine "$fusion360starter"

**Comment by vasiaplaton** [comment]
Hello, thanks for answer. Here's output


      vasia@vasia-pc:~$ fusion360starter="$(find /media/vasia/HDD1TB/Fusion360 -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.wineprefixes/fusion360" wine "$fusion360starter"
      
      002c:fixme:winediag:LdrInitializeThunk wine-staging 6.18 is a testing version containing experimental patches.
      002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
      0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0034:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      006c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      007c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      007c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0090:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0090:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      002c:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      00c4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      00c4:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0108:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0024:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0110:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000003C30000)
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F180 63 ) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makexloc (000000000011F180 63 000000001E1F39B0 0000000000000000) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makewloc (000000000011F180 63 000000001E1F39B0 0000000000000000) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makeushloc (000000000011F180 63 000000001E1F39B0 0000000000000000) semi-stub
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (000000000D0E0000)
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011ED88 1 C) semi-stub
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (00000000119C0000)
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EED0 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF00 1 C) semi-stub
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (00000000135D0000)
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000013720000)
      0110:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000012F20000)
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EE20 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011ED30 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F050 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EF90 1 C) semi-stub
      0110:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
      0110:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011EE24, 000000000011EE40 000000000011EE20
      0110:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011EE24 000000000011EE40 000000000011EE20) returning a dummy value (current locale)
      0110:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011E230 0000000000000000 000000000011E234) returning a dummy value (current locale)
      0110:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011E230 000000001EA10820 000000000011E234) returning a dummy value (current locale)
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011DFB0 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011EEC0 1 C) semi-stub
      0110:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011F0E0 63 C) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makexloc (000000000011F0E0 63 000000001EE1D740 0000000000000000) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makewloc (000000000011F0E0 63 000000001EE1D740 0000000000000000) semi-stub
      0110:fixme:msvcp:locale__Locimp__Makeushloc (000000000011F0E0 63 000000001EE1D740 0000000000000000) semi-stub
      wine: Call from 000000007B01184E to unimplemented function msvcp140.dll.?table@?$ctype@D@std@@QEBAPEBFXZ, aborting
      0110:err:module:LdrInitializeThunk "ContentService.dll" failed to initialize, aborting
      0110:err:module:LdrInitializeThunk Initializing dlls for L"Z:\\media\\vasia\\HDD1TB\\Fusion360\\drive_c\\Program Files\\Autodesk\\webdeploy\\production\\1bc48b96e2e48e9445cd9390dcacb966164222c9\\Fusion360.exe" failed, status 80000100
