### ISSUE TITLE
Runnig Startscript results in file not found. *solved*

### ISSUE THREAD

**Issue by lord-x-type** [cryinkfly/Fusion-360---Linux-Wine-Version-#13]
Running you fusion360-start.sh results in an:
`file not found` Error.

I changed the code line form:
`env WINEPREFIX="/$HOME/$USER/.fusion360" wine C:\\windows\\command\\start.exe /Unix /$HOME/$USER/.fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.link`

to
``env WINEPREFIX="/$HOME/.fusion360" wine C:\\windows\\command\\start.exe /Unix /$HOME/.fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.link``

Running it on Manjaro letest from home dierctory.

and it worked like a charm :+1: 

Keep up the great work!

**Comment by cryinkfly** [comment]
@lord-x-type Thank you for this report!!! :-)

I have changed this in my script: "fusion360-start.sh"
