### ISSUE TITLE
"ContentService.dll" failed to initialize

### ISSUE THREAD

**Issue by bbernhard** [cryinkfly/Fusion-360---Linux-Wine-Version-#14]
Hi,

I've just installed Fusion360 with the `fusion360-install.sh` script on my Lenovo T460s with a freshly deployed Ubuntu 20.04 (not sure yet if this laptop will be powerful enough for Fusion360, but I want to give it a try. Up to now, I am using a Dell laptop with similar specs with Windows 10 for Fusion360 and it works pretty well). But unfortunately when I try to start the application, it fails with:

```
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0118:fixme:shcore:SetCurrentProcessExplicitAppUserModelID L"AutodeskInc.Fusion360": stub
0120:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0120:fixme:font:get_name_record_codepage encoding 20 not handled, platform 1.
0120:fixme:process:GetActiveProcessorGroupCount semi-stub, always returning 1
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E680 63 ) semi-stub
0120:fixme:msvcp:locale__Locimp__Makexloc (000000000011E680 63 000000001D9EA790 0000000000000000) semi-stub
0120:fixme:msvcp:locale__Locimp__Makewloc (000000000011E680 63 000000001D9EA790 0000000000000000) semi-stub
0120:fixme:msvcp:locale__Locimp__Makeushloc (000000000011E680 63 000000001D9EA790 0000000000000000) semi-stub
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (000000000B300000)
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E368 1 C) semi-stub
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (000000000BA20000)
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E2F0 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E310 1 C) semi-stub
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000012E10000)
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000012F60000)
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (0000000012760000)
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E240 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E170 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E470 1 C) semi-stub
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011D800 0000000000000000 000000000011D804) returning a dummy value (current locale)
0120:fixme:nls:get_dummy_preferred_ui_language (0x8 000000000011D800 000000001E304330 000000000011D804) returning a dummy value (current locale)
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011D5C0 1 C) semi-stub
0120:fixme:file:NtLockFile I/O completion on lock not implemented yet
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E420 1 C) semi-stub
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E480 1 C) semi-stub
0120:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0120:fixme:nls:RtlGetThreadPreferredUILanguages 00000038, 000000000011E324, 000000000011E340 000000000011E320
0120:fixme:nls:get_dummy_preferred_ui_language (0x38 000000000011E324 000000000011E340 000000000011E320) returning a dummy value (current locale)
0120:fixme:vcruntime:__telemetry_main_invoke_trigger (000000001A390000)
0120:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (000000000011E5E0 63 C) semi-stub
0120:fixme:msvcp:locale__Locimp__Makexloc (000000000011E5E0 63 000000001E6433C0 0000000000000000) semi-stub
0120:fixme:msvcp:locale__Locimp__Makewloc (000000000011E5E0 63 000000001E6433C0 0000000000000000) semi-stub
0120:fixme:msvcp:locale__Locimp__Makeushloc (000000000011E5E0 63 000000001E6433C0 0000000000000000) semi-stub
wine: Call from 000000007B01188E to unimplemented function msvcp140.dll.?table@?$ctype@D@std@@QEBAPEBFXZ, aborting
0120:err:module:LdrInitializeThunk "ContentService.dll" failed to initialize, aborting
0120:err:module:LdrInitializeThunk Initializing dlls for L"C:\\Program Files\\Autodesk\\webdeploy\\production\\9b196c6eb71126665f61dbf5a4b48d188eb6263c\\Fusion360.exe" failed, status 80000100
```

Has anyone seen this?

I do not have any experience with WINE, so any help is greatly appreciated!

Thanks,
Bernhard

**Comment by dreamcat4** [comment]
type winecfg with the $WINEPREFIX set to the fusion360 wine prefix folder
click libraries tab
it lists all the installed wine dlls there
as for what they are right now, you need to scroll the list and post some screen grabs here

seeing that might help to identify any configuration issue

**Comment by bbernhard** [comment]
> type winecfg with the $WINEPREFIX set to the fusion360 wine prefix folder
> click libraries tab
> it lists all the installed wine dlls there
> as for what they are right now, you need to scroll the list and post some screen grabs here
> 
> seeing that might help to identify any configuration issue

Thanks for your quick reply!

Are there any specific DLLs you are particularly interested in?

I can of course screenshot all the installed DLLs, but this will probably end up in a lot of screenshots (~10-20 screenshots).

**Comment by cryinkfly** [comment]
@bbernhard Go into your $WINEPREFIX and there you can a file "_user.reg_".

In this file you must scroll down to [Software\\Wine\\DllOverrides] and there you can see a list of your DLL's. :-)

---

This is my list:

"*api-ms-win-crt-conio-l1-1-0"="native,builtin"
"*api-ms-win-crt-heap-l1-1-0"="native,builtin"
"*api-ms-win-crt-locale-l1-1-0"="native,builtin"
"*api-ms-win-crt-math-l1-1-0"="native,builtin"
"*api-ms-win-crt-private-l1-1-0"="native,builtin"
"*api-ms-win-crt-runtime-l1-1-0"="native,builtin"
"*api-ms-win-crt-stdio-l1-1-0"="native,builtin"
"*api-ms-win-crt-time-l1-1-0"="native,builtin"
"*atl140"="native,builtin"
"*concrt140"="native,builtin"
"*msvcp140"="native,builtin"
"*msvcp140_1"="native,builtin"
"*msvcp140_2"="native,builtin"
"*msvcr140"="native,builtin"
"*msxml4"="native,builtin"
"*ucrtbase"="native,builtin"
"*vcomp140"="native,builtin"
"*vcruntime140"="native,builtin"

**Comment by bbernhard** [comment]
> @bbernhard Go into your $WINEPREFIX and there you can find a file with this name: _user.reg_
> 
> In this file you must scroll down to [Software\Wine\DllOverrides] and there you can see a list of your DLL's. :-)
> 
> This is my list:
> 
> "*api-ms-win-crt-conio-l1-1-0"="native,builtin"
> "*api-ms-win-crt-heap-l1-1-0"="native,builtin"
> "*api-ms-win-crt-locale-l1-1-0"="native,builtin"
> "*api-ms-win-crt-math-l1-1-0"="native,builtin"
> "*api-ms-win-crt-private-l1-1-0"="native,builtin"
> "*api-ms-win-crt-runtime-l1-1-0"="native,builtin"
> "*api-ms-win-crt-stdio-l1-1-0"="native,builtin"
> "*api-ms-win-crt-time-l1-1-0"="native,builtin"
> "*atl140"="native,builtin"
> "*concrt140"="native,builtin"
> "*msvcp140"="native,builtin"
> "*msvcp140_1"="native,builtin"
> "*msvcp140_2"="native,builtin"
> "*msvcr140"="native,builtin"
> "*msxml4"="native,builtin"
> "*ucrtbase"="native,builtin"
> "*vcomp140"="native,builtin"
> "*vcruntime140"="native,builtin"
> 
> ... and when you have a graphics card like as me, then it's also important, that you install and update your drivers!

Thanks for your help!

I just had a quick look and there are no DLLs listed inside the `[Software\\Wine\\DllOverrides]` section. Should they be there after running `fusion360-install.sh` or do I have missed a step in the README?

**Comment by cryinkfly** [comment]
@bbernhard Okay. It‘s so, when you use my file fusion360-install.sh , then you get the newest wine and winetricks version.

… and with winetricks you get all these DLL‘s. 😊

**Comment by bbernhard** [comment]
> Can you check, if you can see the DLL‘s with the GUI (winecfg).

It's also empty (see attached screenshot)

![Screenshot from 2021-05-15 03-05-33](https://user-images.githubusercontent.com/5710631/118351577-227aef00-b55d-11eb-8fd9-f3811a9d3d92.png)

Stupid me. I just realized that I was looking at the `New Override for library` all the time (that's the list I wanted to screenshot when @dreamcat4 asked me to), but it's actually the `Existing Overrides` that are of relevance here. Sorry for the confusion!

So looks like both the config and the GUI are actually showing the same result - there are no DLLs listed. 

Stupid question, but how do I add those DLLs? Can I just copy the DLL list you've posted above inside the `[Software\\Wine\\DllOverrides]` section or do I need to do something different here?

**Comment by cryinkfly** [comment]
Can you go to your folter Downloads an run this command: WINEPREFIX=~/.fusion360 sh winetricks corefonts vcrun2017 msxml4 win10 

Then you must see all the DLL‘s.

—-

> Can I just copy the DLL list you've posted above inside the [Software\\Wine\\DllOverrides] section or do I need to do something different here?

Yes you can!!! 👍 This is also a way for users they have deleted the DLL‘s or so. 😅

**Comment by bbernhard** [comment]
> WINEPREFIX=~/.fusion360 sh winetricks corefonts vcrun2017 msxml4 win10

Awesome, that worked great - Fusion360 is now starting!

Many thanks for your your help on this!
