### ISSUE TITLE
Broken installation in russian locale  *solved*

### ISSUE THREAD

**Issue by dvilker** [cryinkfly/Fusion-360---Linux-Wine-Version-#15]
Try to start after installation and get message box "Путь не найден" (Path is not found).
Run scripts with LANG=en_US.utf8 is workaround this issue.

P.S.
In fusion360-start.sh instead ".../$HOME/$USER/.fusion360..." there should be ".../$HOME/.fusion360...". $HOME already contains user name.

**Comment by dvilker** [comment]
P.S.S. Today you are is the greatest man of the day! Thank you for you work!

**Comment by cryinkfly** [comment]
@dvilker You're welcome! 😊

> Try to start after installation and get message box "Путь не найден" (Path is not found).
Run scripts with LANG=en_US.utf8 is workaround this issue.

Thank you for this report! 👍
