### ISSUE TITLE
Drawing Workbench dosn't work *solved*

### ISSUE THREAD

**Issue by dvilker** [cryinkfly/Fusion-360---Linux-Wine-Version-#17]
Trying to create Drawing of some and get error message:
Fusion 360 drawings cannot launch...

![image](https://user-images.githubusercontent.com/16972704/118378430-84c70480-b5dc-11eb-84a2-7e67ed02923a.png)

**Comment by cryinkfly** [comment]
@dvilker Yes I know. :-) That's the reason why you can read this in my README.md :D

![Bildschirmfoto_2021-05-16_09-59-02](https://user-images.githubusercontent.com/79079633/118390052-5faeb200-b62d-11eb-826d-25499c68bd54.png)

---

But I'm already in the process of solving this problem. :-)

**Comment by cryinkfly** [comment]
This is the current problem:

https://user-images.githubusercontent.com/79079633/118395611-8c71c200-b64b-11eb-8fee-ca0e3d95daa0.mov

**Comment by cryinkfly** [comment]
Here can you see, what's happened, when I will change the workspace: [error.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6506080/error.txt)

**Comment by cryinkfly** [comment]
So, I have found maybe the reason, why it doesn't work correctly, when I read this post here:

- https://knowledge.autodesk.com/de/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/DEU/Fusion-360-Drawing-cannot-launch.html

It looks like so that we need DXVK and some DLL's to get this workspace to running, but I will check this in the next time! :-)

**Comment by cryinkfly** [comment]
I have tested this with DXVK and other configuration, but it doesn't work at the moment!

Here is the a file: [backtrace.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6835881/backtrace.txt)

**Comment by Tony763** [comment]
With wine 6.15 it's still not running. I opened a bug in wine Bugzilla [51664](https://bugs.winehq.org/show_bug.cgi?id=51664).

**Comment by Tony763** [comment]
Hi @cryinkfly,  I run version 2.0.10806 on wine-staging 6.15, OpenGL core and Drawings works. I just need to sometime zoom in/out when I run mouse over interface, screen gray out. 

My start script:
```bash
env WINEDEBUG=-all AMD_VULKAN_ICD=AMDVLK VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json WINEPREFIX="/home/tony/aplications/fusion360" gnome-terminal --window-with-profile=WIN_E -e  'wine64 /home/tony/aplications/fusion360/drive_c/Program\ Files/Autodesk/webdeploy/production/4c84784f9b312b4c6ccb78d46529ebb70d7a5a09/Fusion360.exe'
```

![image](https://user-images.githubusercontent.com/5598750/130616328-ffce7d77-7f39-4dba-b2af-2a6afafd9b6d.png)

**Comment by cryinkfly** [comment]
@Tony763 Thank you so much for this information!!!

I have tested this on my system with a NVIDIA graphics card and without your extra options:

> steve@cryinkfly-studio:~/.wineprefixes/fusion360/drive_c/Program Files/Autodesk/webdeploy/production/2719e3c6bed8896e3c7319fbb8bfbceff8f489a4> **WINEPREFIX="/home/steve/.wineprefixes/fusion360" wine Fusion360.exe**

... and it works very well!!!

![drawing_bearing.png](https://raw.githubusercontent.com/cryinkfly/Fusion-360---Linux-Wine-Version-/main/images/drawing/drawing_bearing.png)

> I just need to sometime zoom in/out when I run mouse over interface, screen gray out.

I have the same issue, but it is not so bad. The important thing now is that it works at all and that it can be used. :+1: 

---

Can you please check whether this part of the command could also be left out on your system?

> WINEDEBUG=-all AMD_VULKAN_ICD=AMDVLK VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json

**Comment by Tony763** [comment]
Hi @cryinkfly  I have to specify them as I have 3 GPU's. Integrated Intel, Dedicated Nvidia and AMD in External M.2 dock so these commands are just specific to my PC to select correct gpu.

**Comment by cryinkfly** [comment]
@Tony763 Okay, very nice setup! ^^ 

... and thanks for your reports and help! :1st_place_medal: 

I mentioned you here: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/COMMUNITY.md

**Comment by Tony763** [comment]
Wow, Thanks. :slightly_smiling_face:

**Comment by cryinkfly** [comment]
I have created a program launcher for all users the have selected the standard installation path: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/70 :+1:

**Comment by cryinkfly** [comment]
@Tony763 Can you give me some information about you graphic cards [here](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/30)?

**Comment by Tony763** [comment]
@cryinkfly sure, but Im doing some changes right now so I will post them sometime in middle of next week.

**Comment by cryinkfly** [comment]
Here is another issue: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/108
