### ISSUE TITLE
The Python version plays an important role!

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Fusion-360---Linux-Wine-Version-#18]
### The Python version plays an important role!

Now, we dosn't need this step anymore, because every Linux distribution uses a newer Python version now and so I think it's also important to check also a newer Python version with Autodesk Fusion 360 here on Linux. :-)

![Bildschirmfoto_2021-05-16_10-20-35](https://user-images.githubusercontent.com/79079633/118390625-5f63e600-b630-11eb-826b-e2768e3a96d7.png)

**Comment by Tony763** [comment]
Hi, is this necessary?  Installer run its own version of python (3.7).

**Comment by ManuGithubSteam** [comment]
Yes this is necessary as it will force the installer to run even if it does not detect a Windows OS. This has nothing to do with the Python version it just downloaded a unfuckedup version of platform.py from pythons so it does not have to use the one from autodesk wich will not let us run the installer in linux or mac. then it makes sure to run the installer.

**Comment by Tony763** [comment]
I'm referring to issue #12 as newest installers does not contain broken 'platform.py'. I reinstalled fusion a week ago and it worked without this.
