### ISSUE TITLE
Sign in Failure

### ISSUE THREAD

**Issue by Judoguy12** [cryinkfly/Fusion-360---Linux-Wine-Version-#21]
On fedora 34 it loads but I get a popup saying sign in failed contact support

**Comment by cryinkfly** [comment]
@Judoguy12 Okay, can you tell me more about your system, please? 😊

Then I have tested the installation again and it works on Fedora 34 without any problems.

**Comment by Judoguy12** [comment]
that's gone away now but it fails to connect to the internet when its loaded so can't load any of my online designs. Its fedora 34 on a Lenovo Yoga C740

**Comment by lord-x-type** [comment]
Hi, had the same problem.
 Have you tried installing
winehttp
With winetricks in your environment?
This and the command:

sudo setcap cap_net_raw+epi /usr/bin/wine-preloader

Did the trick for me :)

See:

https://wiki.winehq.org/FAQ#Failed_to_use_ICMP_.28network_ping.29.2C_this_requires_special_permissions

I hope this helps :)

**Comment by cryinkfly** [comment]
No, I have only installed Fedora 34 again on my system and after the installation I have activated the Nvidia-Repository.
Then I have installed the newest driver and install Autodesk Fusion 360 with my ![Installation-Script](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/scripts/fusion360-install.sh)

---

![Bildschirmfoto_2021-05-19_09-35-48](https://user-images.githubusercontent.com/79079633/118773966-a0a10380-b885-11eb-8d34-629da59f6adc.png)

That's not a good idea! ;-)

**Comment by Judoguy12** [comment]
I could install winehttps but setcap errors with failed to set capabilities on file 'wine-preloader' (Invalid Argument)

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by cryinkfly** [comment]
@Judoguy12 Can you check, if you can see these DLL's: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/14#issuecomment-841216400

**Comment by Judoguy12** [comment]
[Software\\Wine\\DllOverrides] 1621409851
#time=1d74c81d3a74d04
"*winhttp"="native,builtin"


this is all I have

**Comment by cryinkfly** [comment]
Okay, if I got that right, then you must run this command: 

> WINEPREFIX=~/.fusion360 sh winetricks corefonts vcrun2017 msxml4 win10

**Comment by Judoguy12** [comment]
Apparently there is no fusion 360 folder

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by cryinkfly** [comment]
@Judoguy12 Okay. ;-) 

The best way is you start all over again! :-)

The first one you check if your system is up to date!

Then you do this steps here:

![Bildschirmfoto_2021-05-20_16-23-23](https://user-images.githubusercontent.com/79079633/118995858-c282af00-b987-11eb-908a-158918e3d371.png)

When you have done that, you remove all these things into your Downloads folder: fusion360-install.sh, winetricks and fusion360 (folder).

Also you must remove the folder "fusion360" into your home folder and uninstall wine! 
When you can't see this folder, then you must activate the option "show all hidden files" into your file-browser.

Then download the latest version of my ![Installation-Script](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/scripts/fusion360-install.sh)

And now you install Autodesk Fusion 360 again! :-)

**Comment by cryinkfly** [comment]
### I think it's probably related to this problem: ![https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/23](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/23)

So I'm closing this issue for the moment!

**Comment by cryinkfly** [comment]
I reopen this issuse, because some users get this failure at the moment:

![sign-in-failure](https://user-images.githubusercontent.com/79079633/120856539-50fa5180-c580-11eb-98c7-d95bf311f60f.png)

**Comment by cryinkfly** [comment]
Okay I have found out that the configuration file "NMachineSpecificOptions.xml" is the problem, why some users get this error!

### Solution:

- Open your FIle-Browser

- Go into this folder: /.fusion360/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform/Options/

- Delete this file "NMachineSpecificOptions.xml 

- Restart Autodesk Fusion 360

**Comment by Rohan-Bansal** [comment]
@cryinkfly I do not have a file called NMachineSpecificOptions.xml. I opened the folder you specified and it is empty. Perhaps because I've never been able to log in? I launch the program and it gives me this error, and I am forced to close it.

**Comment by cryinkfly** [comment]
You can copy the content ("NMachineSpecificOptions.xml") from my ![Installation-Script](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/scripts/fusion360-install.sh)! :-)

![NMachineSpecificOptions xml](https://user-images.githubusercontent.com/79079633/120859203-29a58380-c584-11eb-9a3d-15386557412e.png)

**Comment by Rohan-Bansal** [comment]
@cryinkfly I still have the same issue.... Using the options did not help.

**Comment by cryinkfly** [comment]
@Rohan-Bansal Can you visit this site here: https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/Sign-in-Failure-There-was-an-error-logging-in-when-launching-Fusion-360-after-changing-timezones.html

**Comment by Rohan-Bansal** [comment]
Yes, I checked that site and many others already. My timezone is perfectly synced already, I have no idea what's going wrong.

**Comment by cryinkfly** [comment]
So I have tested Autodesk Fusion 360 on my system with Ubuntu 20.04, 20.10 and 21.04.

It works for me! 😅

I don’t know, why it doesn’t work on your system. 😔

**Comment by cryinkfly** [comment]
Can you testing my new installation-script. 🕛

**Comment by cryinkfly** [comment]
I have changed my installation-script (Support Arch Linux & Void Linux)!
