### ISSUE TITLE
Thank you for your work! *solved*

### ISSUE THREAD

**Issue by etinaude** [cryinkfly/Fusion-360---Linux-Wine-Version-#22]
I've been trying to get fusion running on Linux for ages and it finally worked. Thank you so much!

**Comment by cryinkfly** [comment]
You are welcome. 😊

**Comment by dvilker** [comment]
I joined! Thank you man!

**Comment by lord-x-type** [comment]
Love this project too!
Tryed to install fusion with an old tutorial for wine..3 years ago.. It worked, but was very ..unconfortable.

Now with your scripts.. It is super easy and i want to say thanks too!
Nice work :)

**Comment by suryanisaac** [comment]
Same here @cryinkfly, I can't thank you enough. I've been trying for months and it's finally working.

Going to try to get fusion to connect to the cloud now.
