### ISSUE TITLE
Fusion 360 doesn't connect with cloud *solved*

### ISSUE THREAD

**Issue by midtbo** [cryinkfly/Fusion-360---Linux-Wine-Version-#23]
Hi,
Great work making fusion work on linux!
I installed it on Debian 11 and it worked right out of the box. Now i have installed it on Ubuntu 21.04.
It seems to be some problem refreshing online files now, i manage to log in. 

"Having difficulty establishing a connection. We'll keep trying."

I have checked that i do have all the DLL's, and i manage to ping if i run wine cmd ping etc.
![screen](https://user-images.githubusercontent.com/16806739/118939302-d1e60600-b94f-11eb-8f92-3e2013f1f0c5.jpg)

wine-6.8 (Staging)

**Comment by cryinkfly** [comment]
@midtbo  Please do these steps. :-)

![Bildschirmfoto_2021-05-20_16-23-23](https://user-images.githubusercontent.com/79079633/118995858-c282af00-b987-11eb-908a-158918e3d371.png)

**Comment by zmontross** [comment]
I'm having the same problem on Linux Mint 20.x.
My `/etc/hosts` file looks identical to that picture.

**Comment by nyahwhy** [comment]
Same problem on archlinux (fusion works fine in virtualbox win10)

Tried with no luck:
- wine and wine-staging 6.8
- adjusting hosts & hostname didn't change anything
- $ sudo setcap cap_net_raw+epi /usr/bin/wine64-preloader
- Turned off ufw / vpn
- gnutls and lib32-gnutls are installed

**Comment by midtbo** [comment]
> @midtbo Please do these steps. :-)
> 
> ![Bildschirmfoto_2021-05-20_16-23-23](https://user-images.githubusercontent.com/79079633/118995858-c282af00-b987-11eb-908a-158918e3d371.png)

Hi, 
Added last line of hosts, but didn't help. 
Same as the replies above. Really hope we can make this work!

**Comment by dreamcat4** [comment]
https://gist.github.com/probonopd/0fab254aa0b6fc371d8db641822bd530#gistcomment-3751654

**Comment by KIRINN7007** [comment]
> @midtbo Please do these steps. :-)
> 
> ![Bildschirmfoto_2021-05-20_16-23-23](https://user-images.githubusercontent.com/79079633/118995858-c282af00-b987-11eb-908a-158918e3d371.png)

What should I change in /etc/hostname?

**Comment by cryinkfly** [comment]
Some Linux distribution doesn't configured this correctly!

... and this is the reason why I share this.

![network](https://user-images.githubusercontent.com/79079633/119143818-561bb480-ba48-11eb-8078-31c8e855bf42.png)

**Comment by cryinkfly** [comment]
### As I already thought, packages are missing here again!

... and this is the reason, why I also testing Autodesk Fusion 360 with Flatpak. ;-)

![Bildschirmfoto vom 2021-05-21 15-54-45](https://user-images.githubusercontent.com/79079633/119149409-c842c800-ba4d-11eb-8e45-461ddee16dd9.png)
![Bildschirmfoto vom 2021-05-21 15-59-15](https://user-images.githubusercontent.com/79079633/119149416-c8db5e80-ba4d-11eb-90d3-d5f97529defd.png)
![Bildschirmfoto vom 2021-05-21 15-59-53](https://user-images.githubusercontent.com/79079633/119149419-c973f500-ba4d-11eb-975d-a6eb49f76122.png)

**Comment by cryinkfly** [comment]
### Here is the same problem on Windows with a solution:

https://forums.autodesk.com/t5/installation-licensing/fusion-360-doesn-t-connect-with-cloud/m-p/9392312#M237280

![Bildschirmfoto vom 2021-05-21 20-08-04](https://user-images.githubusercontent.com/79079633/119180207-46b06180-ba70-11eb-832b-c98d78136a64.png)


I signed out and signed back in:

![Bildschirmfoto vom 2021-05-21 20-05-30](https://user-images.githubusercontent.com/79079633/119180119-28e2fc80-ba70-11eb-93ca-921701547ab8.png)

I think that they fix now, but it takes a while. ;-)

**Comment by cryinkfly** [comment]
So I did more tests with Ubuntu 21.04 and it still doesn't work!

I have tested this also with the newest wine version 6.9 (devel) and with Flatpak, but I get there the same error.

![Bildschirmfoto vom 2021-05-22 10-16-29](https://user-images.githubusercontent.com/79079633/119219772-7484bd00-bae7-11eb-9b3d-31e681b445ba.png)

**Comment by nyahwhy** [comment]
Mine still works fine in virtualbox, just not with wine. Basic cloud functions are present both in virtualbox and wine - if I log into one, I can log out the other one remotely. 

That AdCefWebBrowser thing on the other hand seems totally broken - not sure if that's required for the side bar stuff.

**Comment by cryinkfly** [comment]
@nyahwhy 

> That AdCefWebBrowser thing on the other hand seems totally broken - not sure if that's required for the side bar stuff.

Okay, I check this now.

**Comment by cryinkfly** [comment]
@nyahwhy 

### So I have tested different configurations with AdCefWebBrowser, but nothing works!

**Comment by cryinkfly** [comment]
So I have created an alternative solution for you so that you can use Autodesk Fusion 360! 
But unfortunately you can't use everything of this program.

Here you can see my alternative way: https://youtu.be/_s42Zb9fnVU

**Comment by cryinkfly** [comment]
### The new product update (v 2.0.10244) still has the problem with the cloud connection!!!

![Bildschirmfoto_2021-05-25_09-29-19](https://user-images.githubusercontent.com/79079633/119457430-f9681480-bd3b-11eb-8692-3532e9873e2c.png)

**Comment by dreamcat4** [comment]
hey @cryinkfly this is why we should not trust autodesk and rely upon fusion. as nice as the software is. but they can choose to change the service at any time. and without any prior notice or warning. leaving you high and dry

this why rhino3d or alibre.is less drama :)
stand alone product

**Comment by cryinkfly** [comment]
@dreamcat4 I believe you about that. But giving up is not my strong point. : D

**Comment by cryinkfly** [comment]
@dreamcat4 I created something here: https://github.com/cryinkfly/Rhino-3D---Linux-Wine-Version-

**Comment by aedancullen** [comment]
I believe this is a TLS-related issue which has always existed with the Wine setup but just didn't manifest itself before. Even though Fusion previously worked fine, its internal diagnostic log would include "Requested web service is unavailable" when it tries to connect to various HTTPS URIs. Perhaps the new update removed a graceful fallback to HTTP, or generally altered something related to this. It appears to be a coincidence that the widely-discussed "issue that could impact your data" is existing at the same time; they are probably not directly related.

**Comment by DD1984** [comment]
Hello,
I found strange issue. When i install fusion on new pc - i have problem with connection to cloud.
But old installation of fusion on laptop (under linux and under windows too) -  work fine. Then i  was copy ".wine" folder from laptop to new pc - and all work fine too.
I find that if file ".wine/drive_c/users/<USER_NAME>/Local Settings/Application Data/Autodesk/Autodesk Fusion 360/CMLWLKHS3A49/NsCloudBrowserCache.dat" contain data (size more than 158b) - cloud services work fine, i can load, delete, create project - all data sync with cloud.
Then i was fully delete fusion under windows and reinstall it - fusion connect to cloud without any problem, i see that fusion create cache file, but name was different - NsCloudBrowserCache_gmail498847.tmp, i rename this file to NsCloudBrowserCache.dat and copy to linux pc.
After that fusion can connect to cloud normally.
Maybe this workaround solution will be helpful for someone.

**Comment by dreamcat4** [comment]
Maybe if we can have a generic (and valid) empty version of this. As an empty data file? Before any real data is written into it. You know just enough to say 'i am empty file'. Perhaps that might help a lot.

**Comment by cryinkfly** [comment]
@DD1984 Thank you very much for this report!!! 👌

**Comment by cryinkfly** [comment]
So I have tested this with a empty file, but this one doesn’t work at the moment. 😅

So I check this with another way.

**Comment by madurani** [comment]
Some smol progres,

I was inspired with a comment from @DD1984. I copied three files from old version of fusion to new affected version **2.0.10244**
from mentioned location location: drive_c/users/<USER_NAME>/Local Settings/Application Data/Autodesk/Autodesk Fusion
and left panel began work:
![image](https://user-images.githubusercontent.com/49711883/120155342-ffa13980-c1f0-11eb-8e92-9206f3567a5b.png)

![image](https://user-images.githubusercontent.com/49711883/120156893-bb169d80-c1f2-11eb-893a-9434b5433619.png)

**Comment by cryinkfly** [comment]
@madurani Very cool ^^ , so we have found a solution for this problem now!!!

**Comment by dreamcat4** [comment]
unfortunately had to delete my existing Fusion360 last week. (out of disk space). So no longer have any copy of this file

**Comment by cryinkfly** [comment]
### Here you can see, how you get to work Autodesk Fusion 360 with the tip from the user @DD1984: 

> https://youtu.be/YUFMcC9qMsY

---

@dreamcat4 I look for a solution, that we doesn't need Windows for this one. :-)
