### ISSUE TITLE
Faild to start Fusion on Fedora 36 *solved*

### ISSUE THREAD

**Issue by vigne** [cryinkfly/Fusion-360---Linux-Wine-Version-#236]
**Describe the bug**
After installing, Fusion shows th Splash screen but after a minute or so terminates/hangs.

**To Reproduce**
* Go to install folder (~/.fusiion360/wineprefix)
* Run '/home/ralph/.fusion360/wineprefixes/box-run.sh'

Alternative:
* Click Fusiobn 360 application icon in launcher

**Expected behavior**
To start Fusion 360

**Desktop (please complete the following information):**
- latest
- Nvidia GTX 3080
- Fedora 36
- Gnome 42
- DXVK

**Additional context**

Here is the output when starting the Fusion 360 from CLI when running ```/home/ralph/.fusion360/wineprefixes/box-run.sh``` from ```/home/ralph/.fusion360/wineprefixes```:

[cli-output.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/8869465/cli-output.log)

Here is the log file from inside the wine drive. It shows plenty of ```function-name not available``` errors I do not understand or know how to fix

[AppLogFile20220609T115542.log](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/files/8869453/AppLogFile20220609T115542.log)

**Comment by clintlombard** [comment]
I'm also seeing the same thing on Manjaro.

**Comment by cryinkfly** [comment]
Under Gnome you have to wait some time, even if it should keep saying that it wants to close the program.

Because when you start Autodesk Fusion 360 for the first time, some Autodesk packages are loaded.

**Comment by clintlombard** [comment]
I'll give it another try and be more patient :sweat_smile:

**Comment by cryinkfly** [comment]
This was the reason also: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/235
