### ISSUE TITLE
Nothing matches org.winehq.flatpak-proton-68-ge-1 in remote flathub *solved*

### ISSUE THREAD

**Issue by dagrende** [cryinkfly/Fusion-360---Linux-Wine-Version-#26]
When I run ./fusion360-flatpak-install.sh it says in the midle smewhere:
error: Nothing matches org.winehq.flatpak-proton-68-ge-1 in remote flathub, 
and then it complains with:
error: app/org.winehq.flatpak-proton-68-ge-1/x86_64/master not installed
I have Ubuntu 21.04 Wayland with Intel® Core™ i7-8650U CPU @ 1.90GHz × 8 
and Mesa Intel® UHD Graphics 620 (KBL GT2).

**Comment by cryinkfly** [comment]
Hey @dagrende 😊,

my script doesn’t work correctly at the moment and so you must do this without my script. 😔
