### ISSUE TITLE
warning: wineserver not found!

### ISSUE THREAD

**Issue by omexlu** [cryinkfly/Fusion-360---Linux-Wine-Version-#27]
I get this error on install:
warning: wineserver not found!

THIS PROBLEM GET SOLVED

But i can't get it run (nothing happends):
./fusion360-start.sh 
16:21 goodpeace@ubuntuN ~/Schreibtisch/TEMP # 01d6:err:ntdll:RtlLeaveCriticalSection section 0x1f06b910 is not acquired
01d6:err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UISettings"
01d6:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Media.ClosedCaptioning.ClosedCaptionProperties"
01d6:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Media.ClosedCaptioning.ClosedCaptionProperties"

**Comment by cryinkfly** [comment]
@omexlu Did you have a different version of wine installed before?

**Comment by omexlu** [comment]
No, new insallation.
But your script don't cover all installation processes of wine.

I can't test because i have deinstalled all.

**Comment by cryinkfly** [comment]
Which Ubuntu version do you use?

**Comment by omexlu** [comment]
Ubuntu 20.04

**Comment by cryinkfly** [comment]
And my script doesn't work on your system? It's strange: ;-)
Can you give me more information, what happens when my script install Autodesk Fusion 360 on your system?

**Comment by omexlu** [comment]
Yes dont work 🙈
I open fusion then it hangs and don't react or the splash screen is with 🙈 noting happends.

**Comment by cryinkfly** [comment]
Can you tell me more about your hardware, please. :-)

**Comment by omexlu** [comment]
Here the output from `hwinfo` (i think here is all you can need) :D
[hardware.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6577311/hardware.txt)

**Comment by cryinkfly** [comment]
Thanks I check this now! :-)

**Comment by cryinkfly** [comment]
Ok I see you use a AMD graphics card. If you using the amdgpu instead of the radeon driver?

**Comment by omexlu** [comment]
Is there no other way so that I can keep the current driver installed? Is the problem with the driver?

**Comment by cryinkfly** [comment]
Open a Terminal and run this command:

> sudo add-apt-repository ppa:oibaf/graphics-drivers && sudo apt update && sudo apt upgrade && sudo apt install libvulkan1 mesa-vulkan-drivers vulkan-utils

Then you check if vulkan is installed correctly with this command: 

> vulkaninfo | less

**Comment by omexlu** [comment]
Currently it is not installed, but I also do not like to install 3 providers software, especially since it is not certain that it is because of that and also possibly still does not work.

Furthermore, I would not use another driver for the graphics card :(

Is there really no other option here?

Lutris hatte ich auch versucht, dort war genau das gleiche Problem :(

**Comment by cryinkfly** [comment]
Since I don't have an AMD graphics card myself, I can't test it. :-(
Da ich leider selber keine AMD Grafikkarte da habe, kann ich es nicht testen . :-(

**Comment by cryinkfly** [comment]
Can you check if you can install this one here?

> sudo apt install mesa-vulkan-drivers mesa-vulkan-drivers:i386
 libvulkan1 libvulkan1:i386

**Comment by omexlu** [comment]
Before I make the effort to try the whole thing again, what about fusion 360, is that completely functional? Are there any bad bugs? And will it be compatible with wine for a long time? 

PS. As far as I know these drivers were installed by Wine.

Thanks for your effort.

**Comment by cryinkfly** [comment]
I can unterstand you! :-(

Can you run this command and send me the output: 

> glxinfo | grep version

**Comment by omexlu** [comment]
I am trying now to install it on a very old laptop to see if it works there :)

Output of the command on my main PC:
`server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6
OpenGL core profile shading language version string: 4.60
OpenGL version string: 4.6 (Compatibility Profile) Mesa 20.2.6
OpenGL shading language version string: 4.60
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 20.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
    GL_EXT_shader_implicit_conversions, GL_EXT_shader_integer_mix, `

**Comment by cryinkfly** [comment]
It looks like okay for me :-)

> I am trying now to install it on a very old laptop to see if it works there :)

Give me a report of them, when it works, so I can create a manual for users they have the same problem as like you. :-)

**Comment by omexlu** [comment]
By the way something is missing in your installation script:
warning: wineserver not found!

Yes but this old laptop does not have an Nvidia card. 

So not the same problem, I just want to know if it's the graphics card, hence the test :)

**Comment by cryinkfly** [comment]
Did you use the installation with DXVK or without DXVK?

**Comment by omexlu** [comment]
On the old laptop without, wine-stable must be installed here before the install-script, otherwise gibs error messages, for whatever reason.

**Comment by cryinkfly** [comment]
> Yes but this old laptop does not have an Nvidia card.

When this computer use only the integrated graphics card:
https://appdb.winehq.org/objectManager.php?sClass=version&iId=36468&iTestingId=108262&bShowAll=true

**Comment by omexlu** [comment]
On the old laptop is also not working, there is even worse and louder error messages, I can not work on the old laptop is too lame for me, sorry can not test there :/

**Comment by cryinkfly** [comment]
Okay, I thank you anyway for testing! :-)
Another way is, when you test Autodesk Fusion 360 into a Flatpak-Runtime, maybe.

**Comment by omexlu** [comment]
Before I make the effort to try the whole thing again, what about fusion 360, is that completely functional? Are there any bad bugs? And will it be compatible with flatpak for a long time?

**Comment by cryinkfly** [comment]
Here can you read more about this one: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/20#issuecomment-842588558

**Comment by omexlu** [comment]
Thanks for your help i keep you informed :)

**Comment by omexlu** [comment]
Flatpak don't work also, after executing the start script get error about directories are not in path XDG_DATA_DIRS and nothings happends :/

I give up.

**Comment by cryinkfly** [comment]
But you have installed Flatpak before you use my script?

Link: https://youtu.be/BB1THQ733xA

When my script doesn’t work correctly, then must run every command itself. 😅

**Comment by omexlu** [comment]
Yes but still don't work i give up, thanks anyway :)

**Comment by cryinkfly** [comment]
I look in the next time for a solution or maybe can help us another user by this problem. 😊

So please don't give up. 😔

**Comment by omexlu** [comment]
Thanks, you scripts need to be improved :)

Thanks for your time and work.

**Comment by cryinkfly** [comment]
@omexlu So, you are not alone with your problem! 

Here is a link: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/29

**Comment by cryinkfly** [comment]
Can you testing my new installation-script. 🕛
