### ISSUE TITLE
Need a feature: install in another folder.

### ISSUE THREAD

**Issue by vasiaplaton** [cryinkfly/Fusion-360---Linux-Wine-Version-#28]
Hey. It would be great if i can install fusion360 not in my home folder. I can do it by hands, but's its difficult to change all that paths in your script. My home folder is low on free space, and I connected another SSD, but your script can only install fusion 360 and winetricks in my home folder. It would be great if i can install fusion360 and winetrikcs in another dir.

**Comment by cryinkfly** [comment]
@vasiaplaton You can install Autodesk on another disk with this command: 

> WINEPREFIX=/myHDD/.fusion360 sh winetricks -q corefonts vcrun2017 msxml4 fontsmooth=rgb win10

**Comment by cryinkfly** [comment]
I add this option to my graphical installer.

**Comment by cryinkfly** [comment]
So, now You have the option where You can install Autodesk Fusion 360 on another folder!
Here is the link: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/commit/a8df6da5864df934dd0d49e21bf7779b15fc2a25
