### ISSUE TITLE
stopped working after updating Ubuntu

### ISSUE THREAD

**Issue by dvilker** [cryinkfly/Fusion-360---Linux-Wine-Version-#29]
Installed and previously working Fusion stopped working after updating Ubuntu. Previously, it did not start for me if I selected nvidia-driver-460, but it worked with nvidia-driver-450. Now I can't go back to this version. And Fusion displays a bug report window after authorization.

**Comment by dvilker** [comment]
At work (HD Graphics 630, not NVidia) same situation. Previously working and broke after Ubuntu update.

**Comment by cryinkfly** [comment]
@dvilker Thank you for your report! You are not alone with this problem, then some users have the same problem with AMD graphics cards. 😉

Can create a file, when you run Autodesk Fusion360 with the NVIDIA graphics card and then another file with only the integrated graphics card? 😊

**Comment by cryinkfly** [comment]
I have found this issue: https://www.linuxquestions.org/questions/slackware-14/wow-lutris-dxvk-broken-after-nvidia-450-57-update-today-current-4175678996/

**Comment by theol0403** [comment]
Hello, first of all thank you for making this! It is so useful to run fusion on linux.

However, as of a few weeks ago I am having the same error on fedora 35.

Here is the debug log as requested (its absolutely massive):

https://drive.google.com/file/d/1u8RGxTjuKd0e9-3UtIRkD_XtrSXBhCaQ/view?usp=sharing

**Comment by cryinkfly** [comment]
@theol0403 Thank you for this file. 👍

**Comment by ekinyuksel12** [comment]
I switched to Ubuntu 21.04 from POP_OS!. And now fusion360 is goes into bug report after authorization just like the @dvilker 's problem. My nvidia driver version is 465

**Comment by cryinkfly** [comment]
Can you testing my new installation-script: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/38

**Comment by cryinkfly** [comment]
I have changed my installation-script (Support Arch Linux & Void Linux)!

**Comment by cryinkfly** [comment]
Also I think it will be good for all users to look to this issue: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/54

**Comment by theol0403** [comment]
I'm not sure where the problem was fixed (wine/os update, fusion update, or script update), but fusion now works on my machine! Thank you so much!

**Comment by cryinkfly** [comment]
Script-update 😅
