### ISSUE TITLE
wine: cannot find 'C:windowscommandstart.exe'

### ISSUE THREAD

**Issue by SphaeroX** [cryinkfly/Fusion-360---Linux-Wine-Version-#3]
`14.) Run this command: env WINEPREFIX="/home/YOUR_USER_NAME/.wine" wine C:\windows\command\start.exe /Unix /home/YOUR_USER_NAME/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk (Here we opening the program Fusion 360 and this creating some files in our .Fusion360 folder.)
`

give the error 

> wine: cannot find 'C:windowscommandstart.exe'

when i try the same with

**"**C:\windows\command\start.exe**"**

then i get the  error 

```
manuel@manuel-laptop:~$ env WINEPREFIX="/home/manuel/Fusion360" wine "C:\windows\command\start.exe" /Unix /home/manuel/Fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk
000d:err:module:__wine_process_init L"C:\\windows\\system32\\winemenubuilder.exe" not found
000b:err:wineboot:process_run_key Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (126).
0016:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\NDIS": 00000001
0009:err:exec:shellex_load_object_and_run failed to get data object

```

and the wine windows opens with an error

`path not found`

**Comment by cryinkfly** [comment]
Your problem is, your command is wrong. ;)

Run this one: env WINEPREFIX="/$HOME/manuel/.wine" wine C:\\windows\\command\\start.exe /Unix /$HOME/manuel/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk

Now it should works for you. :)
