### ISSUE TITLE
Clicking certain UI elements causes Fusion 360 to crash

### ISSUE THREAD

**Issue by zakutin** [cryinkfly/Fusion-360---Linux-Wine-Version-#315]
**Describe the bug**
Fusion crashes and exits with error when clicking certain UI elements.

The list of UI elements causing Fusion to crash:
- Right click in browser tree, "do not capture design history" first, and then "capture design history"
- "Close sign" on the orange message about graphics performance
- "Finish edit in place" button (both, on the top of the screen or right click in browser tree)
- (to be added)

**Desktop:**
- Version number of Autodesk Fusion 360: 2.0.15509 x86_64
- Graphics card model + Graphics card driver (Version number): 
    - Vendor: Intel (0x8086)
    - Device: Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
    - Version: 22.3.7
- Operating system: Fedora 37 Workstation
- Kernel: 6.2.7-200.fc37.x86_64
- Desktop environment: GNOME 43.3, both X11 or Wayland
- DXVK- or OpenGL-Mode: both
- Wine 8.4

**Additional context**
<details>
<summary>Error message after crash</summary>

```
MAG.Default: [Idle Status] Report Idle(Idle or Not):  false
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
036c:err:d3d:wined3d_context_gl_set_pixel_format wglSetPixelFormatWINE failed to set pixel format 1 on device context 000000001001010F.
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x1006ab0
  Serial number of failed request:  61562
  Current serial number in output stream:  61580
15:31:17 [socket]: Client has disconnected...
0408:fixme:manipulation:viewport_Abandon 0000000000413A30
15:31:17 [socket]: Client is no longer running. Will terminate.
15:31:17 Shutting down FremontJS [Client socket disconnected]...
0408:fixme:manipulation:viewport_Abandon 0000000000383940
15:31:17 ...Server disconnected
15:31:17 ...Commands of SDKInstance f253c718-b050-48da-be5d-1665b2e22d4a:https:/
/developer.api.autodesk.com/assetgraph:co.JmDbbGBVRP-GulrZSncgHA completed
15:31:17 ...SDKInstance f253c718-b050-48da-be5d-1665b2e22d4a:https://developer.a
pi.autodesk.com/assetgraph:co.JmDbbGBVRP-GulrZSncgHA disposed
15:31:17 Exiting process
0300:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011E360
[ea@t480 ~]$ 0408:fixme:iphlpapi:CancelIPChangeNotify (overlapped 0000000009CDF5F8): stub
03f4:fixme:wtsapi:WTSUnRegisterSessionNotification Stub 0000000000010144
0108:fixme:ver:GetCurrentPackageId (000000000021FD70 0000000000000000): stub
0130:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\ea\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\21e48068-b078-4fa7-8d8d-c3f544af06c7_i4.json.user.saving", 0x00000001, 0000000000000000, 000000000011E970): stub
0130:fixme:mpr:WNetGetUniversalNameW (L"C:\\users\\ea\\AppData\\Roaming\\Autodesk\\ADPSDK\\JSON\\21e48068-b078-4fa7-8d8d-c3f544af06c7_i4.json.user", 0x00000001, 0000000000000000, 000000000011E970): stub
0140:fixme:ver:GetCurrentPackageId (000000000021FD70 0000000000000000): stub

```

</details>

**Comment by lorn10** [comment]
I have no idea if the following will help here anything but such problems like this here _could_ be resolved sometimes by using a (different) native `gdiplus.dll` file. However, stay away from the old old variant in winetricks.

Howto: Get the first `gdiplus.dll` (10.0.17763.1) from [here](https://www.dll-files.com/gdiplus.dll.html). Place it next to the Fusion360.exe and make an override in winecfg for `gdiplus.dll`. :+1: 

More information can be found here:
https://github.com/Winetricks/winetricks/issues/1840

**Comment by lorn10** [comment]
I make the override always via `winecfg`, so enter `winecfg` at the CLI and select the section "libraries". There you can add the `gdiplus.dll` override. :wink:

**Comment by simontipping21** [comment]
> FYI - If I use the latest `GdiPlus.dll` from the link you posted with an override then Fusion crashes on start and is unusable.

So I have extracted a version of `GdiPluss.dll` from a Windows 10 ISO. No crashing when using the override now.

**Comment by lorn10** [comment]
Indeed, there may exists different causes for problems like this here. The `gdiplus.dll` file might be only one factor.  And the behavior could be also be tied to other aspects like which display driver or X server is used and so on.

While I can confirm that a newer `gdiplus.dll` version may work better for some applications there can be also no difference at all.

Regarding **[Paint.NET 3.5.11](https://bugs.winehq.org/show_bug.cgi?id=51561)** I can confirm that so far all native Microsoft gdiplus.dll files are crashing the program. Whatever, the built-in gdiplus.dll variant of Wine gets better and better. So I think it's just a question of time until it reaches the state of the original one. :wink:
