### ISSUE TITLE
Completely uninstalling the package

### ISSUE THREAD

**Issue by suryanisaac** [cryinkfly/Fusion-360---Linux-Wine-Version-#32]
Hey,

I'd like to completely uninstall Fusion360 and reinstall it for troubleshooting. Do you have the locations of the binaries and other related files to delete them? Thanks

**Comment by suryanisaac** [comment]
To add to this, I used the install.sh file, not flatpak

**Comment by cryinkfly** [comment]
@suryanisaac Delete the folder .fusion360 into your folder home. 😊

**Comment by suryanisaac** [comment]
Thank You!

**Comment by buteomont** [comment]
> @suryanisaac Delete the folder .fusion360 into your folder home and then you can reinstall Autodesk Fusion 360. blush

My home folder doesn't have a .fusion360 folder.  has this changed?

**Comment by teackot** [comment]
> My home folder doesn't have a .fusion360 folder. has this changed?
.wineprefixes/fusion360
