### ISSUE TITLE
Can't synchronize with cloud

### ISSUE THREAD

**Issue by BrachyKnight** [cryinkfly/Fusion-360---Linux-Wine-Version-#33]
I really wanna start by thank you, because this is the closest I've been to making fusion 360 work on Linux. I am on gnome wayland on Garuda Linux (a fork of Arch) and for some reason in the left panel (where the projects are usually in) there's a label that says "Having difficulty establishing a connection. We'll keep trying.". I can't continue working offline, because it says that first it needs to connect to the cloud. I had no problem logging in, so in theory it can connect to Internet.
Any tip would be a huge help

**Comment by cryinkfly** [comment]
@BrachyKnight Here is a solution for this problem at the moment: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/releases/tag/v2.6 😊

**Comment by BrachyKnight** [comment]
Thank you! I'm sorry I didn't check the closed issues before opening a new one. Anyway, I'll mark this one as solved!
