### ISSUE TITLE
Freez to a blanck screen when start ./fusion360-start.sh script

### ISSUE THREAD

**Issue by brando16** [cryinkfly/Fusion-360---Linux-Wine-Version-#34]
Hi all,

very good job the software start but no do anything for hours when launch the start script, i work on Imac mid2011 with AMD radeon HD 6970 6990:

sudo lspci
`00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:02.0 Display controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Universal Host Controller #5 (rev 05)
00:1a.7 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b5)
00:1c.1 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b5)
00:1c.2 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 3 (rev b5)
00:1c.4 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 5 (rev b5)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Universal Host Controller #1 (rev 05)
00:1d.7 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation Z68 Express Chipset LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Desktop SATA AHCI Controller (rev 05)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 05)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Blackcomb [Radeon HD 6970M/6990M]
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Barts HDMI Audio [Radeon HD 6790/6850/6870 / 7720 OEM]
02:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM57765 Gigabit Ethernet PCIe (rev 10)
03:00.0 Network controller: Qualcomm Atheros AR93xx Wireless Network Adapter (rev 01)
04:00.0 FireWire (IEEE 1394): LSI Corporation FW643 [TrueFire] PCIe 1394b Controller (rev 08)
05:00.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:00.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:03.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:04.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:05.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
06:06.0 PCI bridge: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]
07:00.0 System peripheral: Intel Corporation CV82524 Thunderbolt Controller [Light Ridge 4C 2010]`

and uname is:
`Linux iMac-di-Andrea.lan 5.3.18-lp152.75-default #1 SMP Wed May 5 09:22:56 UTC 2021 (16c42c8) x86_64 x86_64 x86_64 GNU/Linux`

The system is opensuse Leap 15.2 the script work fine but not start.

**Comment by cryinkfly** [comment]
Okay can you check, if Autodesk Fusion 360 run without my Start-Script? 😊

**Comment by brando16** [comment]
Sorry, but I can do that? in your start script launch e wine command and I do the same not with your script but my hands so I not understand what I do.

Sorry for my ugly english😅

Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by cryinkfly** [comment]
@brando16 We can also writing in German. 😅

Yes you can, when you change into this folder:

> .fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk

Then you run this command:

> WINEPREFIX=".fusion360" wine Autodesk\ Fusion\ 360.lnk

**Comment by brando16** [comment]
Ok Steve when is possibile I do what you ask me and then tell you what happens

Best regards

Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by cryinkfly** [comment]
Okay, I wait for your answer. 👍

**Comment by dreamcat4** [comment]
hey @brando16 what might help to see is give the log output from the script command. when you run from cmdline. This way there should be some log printed in terminal.

maybe like this:

`sh -x ./SCRIPT.sh`

**Comment by brando16** [comment]
I try what you tell me but nothing start got only this outpt:

 WINEPREFIX="/home/andrea/.fusion360" wine Autodesk\ Fusion\ 360.lnk
> No protocol specified
> No protocol specified
> 0009:err:module:__wine_process_init failed to load
> L"C:\\ProgramData\\Microsoft\\Windows\\Start
> Menu\\Programs\\Autodesk\\Autodesk Fusion 360.lnk", error c000012f
> ***@***.***Mac-di-Andrea:~/.fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start
> Menu/Programs/Autodesk> No protocol specified
> No protocol specified
>
>

*Andrea Manca*
Responsabile Progetti Informatici
phone 3408131435


Il giorno lun 7 giu 2021 alle ore 11:51 Steve Zabka <
***@***.***> ha scritto:

**Comment by cryinkfly** [comment]
@brando16 Have I understood that correctly?

You opened the terminal and change to the correct folder with this command:

> .fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk

and then you have started Autodesk Fusion 360 with this command:

> WINEPREFIX=".fusion360" wine Autodesk\ Fusion\ 360.lnk

**Comment by brando16** [comment]
Yes I do this exact commands from my home, where exist .fusion360:

cd .fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk

And then

WINEPREFIX="/home/andrea/fusion360" wine Autodesk\ Fusion\ 360.lnk
I have to change .fusion with full path if not do it i have and error in this prefix.


Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by dreamcat4** [comment]
do you have a `DISPLAY=` environment variable set for xorg? can you launch other GUI apps from the same terminal session?

**Comment by brando16** [comment]
I can launch another app Kate for exsample or dolphin but I don't know il
the variable DISPLAY exist if I do echo $DISPLAY output is :0


*Andrea Manca*
Responsabile Progetti Informatici
phone 3408131435


Il giorno lun 7 giu 2021 alle ore 12:39 Dreamcat4 ***@***.***>
ha scritto:

**Comment by cryinkfly** [comment]
@brando16  Which desktop environment have you installed on your system?

Can you run this command:

> export DISPLAY=:0

Then do this:

> cd .fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk

and then you have started Autodesk Fusion 360 with this command:

> WINEPREFIX=".fusion360" wine Autodesk\ Fusion\ 360.lnk

**Comment by brando16** [comment]
KDE 

Yes I can do that, but last command not execute if I have to change WINEPREFIX to /home/andrea/.fusion360

That’s ok?

Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by brando16** [comment]
Same error

Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by cryinkfly** [comment]
When you open a terminal, then you can use this command:

> WINEPREFIX=".fusion360" wine Autodesk\ Fusion\ 360.lnk

Did you have also installed the latest graphics driver?

**Comment by brando16** [comment]
I can’t execute the command exatly.
The path WINEPREFIX must be an absolute path.

Yes I have all driver installed.

Andrea Manca
IT Senior Consultant
Mob. +39 3408131435

**Comment by cryinkfly** [comment]
@brando16 I have seen that you will run Autodesk Fusion 360 with a AMD graphics card:

> i work on Imac mid2011 with AMD radeon HD 6970 6990

Can you read this, please:

> https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/wiki/Supported-Graphics-Cards

**Comment by ekinyuksel12** [comment]
I have the same problem too.

Ubuntu 20.10
Intel i7 1065g7
Mx330

**Comment by cryinkfly** [comment]
@ekinyuksel12 Thank you for your report! :-)

**Comment by cryinkfly** [comment]
@brando16 and @ekinyuksel12 

1. Step: Open your File-Browser and delete the folder ".fusion360" into your home folder!

2. Step: Open a Terminal an change to your folder "Downloads" with this command:
> cd Downloads

3. Step: Create a new WINEPREFIX for Autodesk Fusion 360 with this command:
> WINEPREFIX=~/.fusion360 sh winetricks -q corefonts msxml4 vcrun2017

4. Step: Run this command:
> WINEPREFIX=~/.fusion360 sh winetricks win10

5. Step: Change to your fusion360 folder into your folder Downloads with this command:
> cd fusion360

6. Step: Install Autodesk Fusion 360 with this command (2x):
> WINEPREFIX=~/.fusion360 wine Fusion\ 360\ Admin\ Install.exe -p deploy -g -f log.txt --quiet

7. Step: Switch to your File-Browser and go into this folder:
> /home/USERNAME/.fusion360/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform

8. Step: Create a new folder "Optiona" and input the [NMachineSpecificOptions.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6619262/NMachineSpecificOptions.txt) into this folder and change it from .txt to .xml!

9. Step: Open Autodesk Fusion 360 with this command:
> env WINEPREFIX="/$HOME/.fusion360" wine C:\\windows\\command\\start.exe /Unix /$HOME/.fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk

---

When step 9 dosnt work for you @ekinyuksel12 , then you must add this option:
> env WINEPREFIX="/$HOME/.fusion360" optirun wine C:\\windows\\command\\start.exe /Unix /$HOME/.fusion360/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk

---

@brando16 Here you can see, that the user @DD1984 use a AMD Radeon Graphics Ryzen 5 PRO 4650G and it works with Autodesk Fusion 360: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/30#issuecomment-856140418

**Comment by ekinyuksel12** [comment]
I havve tried your steps but no luck still wihte blank screen. But now it gives me a crash reporter.

Wine output:

> 00b7:err:ntdll:RtlLeaveCriticalSection section 0x1ee0bd20 is not acquired
> 00b7:err:combase:RoGetActivationFactory Failed to find library for L"Windows.UI.ViewManagement.UISettings"
> 00b7:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Media.ClosedCaptioning.ClosedCaptionProperties"
> 00b7:err:combase:RoGetActivationFactory Failed to find library for L"Windows.Media.ClosedCaptioning.ClosedCaptionProperties"

![Screenshot from 2021-06-09 10-35-17](https://user-images.githubusercontent.com/53980540/121312821-6ec40f80-c90e-11eb-83e4-f7be55be3254.png)

**Comment by cryinkfly** [comment]
@ekinyuksel12 Maybe it works when you use dxvk. ☹️😊

**Comment by ekinyuksel12** [comment]
Sorry for late answer. I tried that too but no luck. One week ago I switched to Ubuntu 21.04 and the issue seems to be disappear.

**Comment by cryinkfly** [comment]
Okay I think this issue here has some similarities with this one here: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/38

… and so we continue this problem there.
