### ISSUE TITLE
Increase allocated resources?

### ISSUE THREAD

**Issue by BrachyKnight** [cryinkfly/Fusion-360---Linux-Wine-Version-#35]
Right now fusion works fine, but it sometimes can feel sluggish and I think that's because it doesn't use much RAM or system resources. Is there a way to increase that?

**Comment by dreamcat4** [comment]
the speed of fusion is limited by calls to http / https api. this may be limited by the DLL in wine, and as such you are needing to be waiting a lot of time for HTTP calls to return over TCP

a good solution for higher performance is to eliminated this aspect entirely. by switching to a different software such as rhino3d or alibre product(s). which does not do this

however for fusion it is more a question about how much slower the http libraries are under wine. it is important to realize that.
