### ISSUE TITLE
Installation fails on Arch: Multilib is not enabled by default

### ISSUE THREAD

**Issue by Patschke** [cryinkfly/Fusion-360---Linux-Wine-Version-#40]
The install-script (https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/scripts/fusion360-install.sh) will fail on Arch linux by default, since it can't install wine. Wine is available in the multilib, which is not included by default. It will still display `The installation of Autodesk Fusion 360 is completed`.

I suggest to include a check, if multilib is enabled. If it is not, you may ask the user to to un-comment the corresponding entry
```
[multilib]
Include = /etc/pacman.d/mirrorlist
```
in `/etc/pacman.conf` and update (e.g. `pacman -Sy`).

**Comment by Patschke** [comment]
I also needed to install `samba` (since `ntlm_auth` was missing otherwise) and `cabextract` (since wine complained bout that missing as well). So probably something along the lines of `pacman -S samba cabextract`) wouldn't hurt as well?

After installing those I am now at least presented with the Autodesk error report crash screen - a step forward ;-)

**Comment by cryinkfly** [comment]
@Patschke Okay, can you also check if you have installed libGLU1, winbind and also openSSL:

![1505A427-3B52-4200-A285-71D55EF57930](https://user-images.githubusercontent.com/79079633/125085009-6b1cd780-e0ca-11eb-8247-c82e72aa8374.jpeg)

**Comment by Patschke** [comment]
>Okay, can you also check if you have installed libGLU1

Yes, I do have `extra/glu 9.0.2-1` and `multilib/lib32-glu` installed:
```
[patrick@PatricksDesktop]$ sudo pacman -Fyx libGLU.so.1
:: Paketdatenbanken werden synchronisiert …
 core ist aktuell
 extra ist aktuell
 community ist aktuell
 multilib ist aktuell
extra/glu 9.0.2-1 [Installiert]
    usr/lib/libGLU.so.1
    usr/lib/libGLU.so.1.3.1
multilib/lib32-glu 9.0.1-1 [Installiert]
    usr/lib32/libGLU.so.1
    usr/lib32/libGLU.so.1.3.1
```

> winbind

Winbind is installed via `extra/samba 4.14.5-1` (actually wine told me to install winbind when I did not have `ntlm_auth`)

> and also openSSL

I've got `core/openssl 1.1.1.k-1` and `lib32-openssl` installed

I think it would be helpfull, if your installation script checks for those requirements (it will actually happily claim, that Fusion was installed, even if the requirements are in fact not met and Fusion is not installed at all).

**Comment by cryinkfly** [comment]
I have changed my installation-script (Support Arch Linux & Void Linux)! 🚀
