### ISSUE TITLE
fusion360 fails to launch when using fusion360-start.sh

### ISSUE THREAD

**Issue by 00schoeny** [cryinkfly/Fusion-360---Linux-Wine-Version-#44]
I just attempted to install and run fusion for the first time on my ASUS Q550L running Ubuntu 20.04.  

After running the install script i attempted to run the start script, see terminal output below. After the first failed attempt i used ctrl-c to cancel and retried. 

![Screenshot from 2021-07-17 15-04-42](https://user-images.githubusercontent.com/11008229/126048273-47b4728a-a3af-4fa5-8d33-ac7935628fd7.png)

**Comment by 00schoeny** [comment]
sudo apt update fixed my wine issues from the original post.  

i am still getting a failure to load:
![Screenshot from 2021-07-17 15-34-22](https://user-images.githubusercontent.com/11008229/126048775-993c840d-3dcd-4cca-b1c2-cc80f4ea7018.png)

**Comment by cryinkfly** [comment]
@00schoeny Have you installed winbind?

**Comment by marrobHD** [comment]
I installed winbind. Still wont open.
```
may@zorinos-TM1701:~/Schreibtisch$ bash ./fusion360-start.sh 
may@zorinos-TM1701:~/Schreibtisch$ 00c2:err:ntdll:RtlLeaveCriticalSection section 0x1b0f9300 is not acquired
wine: Call from 0x7b02dc26 to unimplemented function ucrtbase.dll.feclearexcept, aborting

```

**Comment by cryinkfly** [comment]
> wine: Call from 0x7b02dc26 to unimplemented function ucrtbase.dll.feclearexcept, aborting

Okay, I know that you can find this DLL in vcrun2015. Can you install it with winetricks?

For example: winetricks -q vcrun2015

**Comment by TerraRoot** [comment]
I'm getting the same issue, 
`$ ./fusion360-start.sh 
$ 002e:err:ntdll:RtlLeaveCriticalSection section 0x1b0fe3b0 is not acquired
wine: Call from 0x7b02dc26 to unimplemented function ucrtbase.dll.feclearexcept, aborting
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
0072:err:winediag:MIDIMAP_drvOpen No software synthesizer midi port found, Midi sound output probably won't work.`

vcrun2015 is installed

**Comment by cryinkfly** [comment]
Okay, read this one: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/38#issuecomment-882031611

**Comment by 00schoeny** [comment]
@cryinkfly still no luck for me after following instructions from the comment linked above and installing vcrun2015 and winbind. same behavior, hanging during startup.

**Comment by TerraRoot** [comment]
deleted NMachineSpecificOptions.xml, no LoginState.xml found, and no change getting the same error.

tried lutris  [#42 (comment)](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/42#issuecomment-881908378)
it started! but now it unable to login, different issue :)

**Comment by cryinkfly** [comment]
@TerraRoot 

> it started! but now it unable to login, different issue :)

Can you tell me more, what you mean about unable to login? 😊

**Comment by marrobHD** [comment]
I'm able to login but the main application won't start up. That means successful login->some minutes a white window->crash window.

**Comment by TerraRoot** [comment]
`0100:fixme:netprofm:connection_GetAdapterId 0000000038A50CE0, 000000005B32B930
07c4:fixme:netprofm:connection_GetAdapterId 00000000200D3220, 000000002434B930
`

it just streams this (using lutris 6.1) i'd love to get more details but for some reason i cannot capture the output,

**Comment by cryinkfly** [comment]
I have deleted my start-script!!!

But here You can find the command for running Autodesk Fusion 360 over the terminal (Example):

![Bildschirmfoto_2021-08-01_18-40-20](https://user-images.githubusercontent.com/79079633/127778901-592cda15-3e52-4988-b1f2-459adcaa7e3d.jpg)
![Bildschirmfoto_2021-08-01_18-40-39](https://user-images.githubusercontent.com/79079633/127778903-f691be51-ff90-4573-bad5-f68cf77e8610.png)
![Bildschirmfoto_2021-08-01_18-41-08](https://user-images.githubusercontent.com/79079633/127778904-9d3412e5-8aaf-4644-8df7-2f72e4fc7069.png)

**Comment by marrobHD** [comment]
Could you please copy paste the start command here? It would be way easier to use than coping it from the screenshot.

**Comment by mavaa** [comment]
```
F360DIR="$HOME/f360"
env WINEPREFIX="$F360DIR" wine C:\\windows\\command\\start.exe /Unix "/home/martin/f360/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk"
```

This worked for me, just replace the content of the F360DIR variable

**Comment by alejojo** [comment]
> ```
> F360DIR="$HOME/f360"
> env WINEPREFIX="$F360DIR" wine C:\\windows\\command\\start.exe /Unix "/home/martin/f360/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk"
> ```
> 
> This worked for me, just replace the content of the F360DIR variable

Thank you @mavaa , let me do small modification to make it usable for everybody:

```bash
F360DIR="$HOME/.wineprefixes/fusion360/"
env WINEPREFIX="${F360DIR}" wine C:\\windows\\command\\start.exe /Unix "${F360DIR}/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk"
```

**Comment by cryinkfly** [comment]
Here you can find more about my new program launcher: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/70
