### ISSUE TITLE
Winbind not installed

### ISSUE THREAD

**Issue by trumpton** [cryinkfly/Fusion-360---Linux-Wine-Version-#45]
I'm having trouble with the installation script, and one of the things I had to do to get things moving along was to install winbind.

I am running Ubuntu 20.04

sudo apt-get install winbind

**Comment by cryinkfly** [comment]
When I use my script then I get winbind installed.

**Comment by cryinkfly** [comment]
So a user with Kubuntu get to running Autodesk Fusion 360 with my new installation script. 👌

Link to this issue: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/50
