### ISSUE TITLE
Suggestion for install attempts without re-downloading

### ISSUE THREAD

**Issue by trumpton** [cryinkfly/Fusion-360---Linux-Wine-Version-#46]
It's taking several attempts with the script to get an install going (still not actually there).
Every time I run the script, it re-downloads many files, including the 1Gb application.

Could the download scripts use wget -c rather than just wget, so that if the file is already there, it is not re-fetched.

Perhaps a --force-redownload switch is necessary to override this, or the downloading of a single md5sum file indicating the latest issue checksums.

**Comment by cryinkfly** [comment]
@trumpton I have solved this problem with re-downloading!

Thank you for your help! 👍
