### ISSUE TITLE
Some problems with Fusion 360 when I use XWayland!

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Fusion-360---Linux-Wine-Version-#47]
If you use Wine on a system with XWayland, then you can activate the option for "Emulating a virtual desktop" in the Graphics Tab in winecfg for to avoid these problems here:

    - flickering
    - wrong window location
    - wrong mouse cursor location and clicks
    - keyboard detection

**Comment by FIXMBR** [comment]
I managed to fix not being able to type in highlighted input boxes in XWayland, without the use of virtual desktop.
I did it by adding custom window rule for fusion360 in KDE settings and setting `Accept focus` to force.
![Screenshot_20220120_104028](https://user-images.githubusercontent.com/16748784/150313757-6428bc1c-a675-4bda-a97f-0fb4bb7f5f7a.png)

**Comment by phrxmd** [comment]
Thanks @FIXMBR, that fixed keyboard input on KWin Wayland for me.

**Comment by gymnae** [comment]
Yeah, also thanks from me, that fixed it :)
