### ISSUE TITLE
Add note in README that the package "dialog" is requred.

### ISSUE THREAD

**Issue by ReubenBTalbott** [cryinkfly/Fusion-360---Linux-Wine-Version-#50]
Hi, spent around an hour trying to figure out why your script wasn't working, turns out it was my distro's fault (Kubuntu) because it didn't have the package "dialog" installed, you may want to put a note about that in the README or add a check in the script.

Thanks!
Reuben Talbott

PS. Thanks for making the script!

**Comment by cryinkfly** [comment]
I have added this package to my README and to my documentation. 👌
