### ISSUE TITLE
The install script simply won't launch *solved*

### ISSUE THREAD

**Issue by Ph4nt0mh4x0r** [cryinkfly/Fusion-360---Linux-Wine-Version-#52]
For some odd reason when I launch the script it does nothing. No welcome screen or anything like that. I did run chmod +x fusion360-install.sh and yet it decided not to run. I am using Manjaro on the 5.10.53-1-MANJARO kernel.

**Comment by ConorIA** [comment]
Just ran into this. The script fails silently if dialog is not installed. `pacman -S dialog`

**Comment by Ph4nt0mh4x0r** [comment]
Oh wack that's interesting. Thanks for letting me know!

**Comment by cryinkfly** [comment]
@Ph4nt0mh4x0r Thats the reason why you look into my [documentation](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/wiki/Documentation). 😅

![446ECBB9-1740-4A3E-9ECA-06111D95497B](https://user-images.githubusercontent.com/79079633/127960645-1677a505-e43e-40a3-897e-ff3a279a2afe.jpeg)

**Comment by ConorIA** [comment]
#51 will help!

**Comment by cryinkfly** [comment]
@ConorIA  Thank you for the help. 😊

I just wanted to point out that you should take a look at the documentation beforehand. 😅
