### ISSUE TITLE
[Not an issue] Fusion360 working under Void Linux

### ISSUE THREAD

**Issue by Le0xFF** [cryinkfly/Fusion-360---Linux-Wine-Version-#53]
As title says, this is not an issue.

I got Fusion360 working on Void Linux and I've documented every step in [my gist](https://gist.github.com/Le0xFF/6d2476c64280e4308664ddf9d12c566f). If you think this could be added to your script, I'll be really glad :smile: 
If you need more infos, ask me anything!

I've also tried Vulkan as renderer with dxvk but sadly with no luck. OpenGL seems the only one that works right now.

Here's a screenshot!
![Fusion360VoidLinux](https://user-images.githubusercontent.com/43521247/127987812-690ad860-81d7-492e-89ae-e80f0e543064.png)

**Comment by cryinkfly** [comment]
@Le0xFF Thank you so much for this report and for your work!!! 👍👌

**Comment by cryinkfly** [comment]
@Le0xFF So, I have added Void Linux to my installation-script! 🚀
