### ISSUE TITLE
Linux Mint 20.2 Support

### ISSUE THREAD

**Issue by mellery** [cryinkfly/Fusion-360---Linux-Wine-Version-#54]
Is linux mint 20.2 supported?  I get an error during install about the wine-staging package, it's version references hirsute, so it's looking for the ubuntu version.

**Comment by cryinkfly** [comment]
Linux Mint 20.2 use Ubuntu 20.04 as basis and so you must select this one. 😊

Link: https://wiki.winehq.org/Ubuntu

**Comment by mellery** [comment]
Thanks, I'm getting broken packages, libc6 in mint 20.2 is at 2.31-0ubuntu9.2

wine-staging:
  Depends: libc6 (>=2.33) but 2.31-0ubuntu9.2 is to be installed
 Depends: wine-staging-i386 (= 6.14~hirsute-1)
 Depends: wine-staging-amd64 but it is not going to be installed

**Comment by cryinkfly** [comment]
Very interesting. 🤔 Then we must search why it’s so.

**Comment by cryinkfly** [comment]
I have found this issue: https://askubuntu.com/questions/1315906/unmet-dependencies-libc6-the-package-system-is-broken

**Comment by cryinkfly** [comment]
@mellery I have change the installation-script! :+1:

**Comment by mellery** [comment]
thanks!  That fixed the installer, I get a blank window after the fusion 360 splash screen closes

**Comment by mellery** [comment]
rebooted and left it open for a long time and it started working!  Thanks for the script!
