### ISSUE TITLE
Enter the path for your Fusion 360?

### ISSUE THREAD

**Issue by azurusnova** [cryinkfly/Fusion-360---Linux-Wine-Version-#55]
It's giving me an example, but I am not sure if thats what I am supposed to use, or if I am to point it to a specific location, or if this is just where I want it to install to.

I need some clarification for this please.

**Comment by cryinkfly** [comment]
You can install it anywhere you want.

For example, you can install it in your home directory (/home/USER/.fusion360) or you install it on a USB stick (/media/usb-drive/.fusion360).

The .fusion360 folder will then be created for you automatically. 😊
