### ISSUE TITLE
Can't make new window

### ISSUE THREAD

**Issue by rusk911** [cryinkfly/Fusion-360---Linux-Wine-Version-#56]
After prompting for installation location script dies with message "Can't make new window at (-1,0), size (25,78)."
OS Linux Mint 20 ulyana.
dialog installed. All installations processed with no issues.

**Comment by rusk911** [comment]
Solved. It appears when a terminal emulator window has standard dimensions. Extending to fullscreen solved the issue.

**Comment by cryinkfly** [comment]
@rusk911 I have changed my script, so we have solved this issue for all users! :rocket: 

Thank you for this report!!! :+1:
