### ISSUE TITLE
sudo: add-apt-repository: command not found

### ISSUE THREAD

**Issue by cooked** [cryinkfly/Fusion-360---Linux-Wine-Version-#57]
Hi,
thanks for this great script. I run into the error above (and the installation failed) since in my system, running Debian 10, the command was missing for some reason.
I solved installing software-properties-common package with the following command
`sudo apt-get install software-properties-common`

Maybe consider adding that as a requirements into the script

cheers
Stef

**Comment by cryinkfly** [comment]
@cooked Thank your for this information! :+1: 

I have added this package to my installation-script. :rocket:
