### ISSUE TITLE
Can't get past this wine-staging error

### ISSUE THREAD

**Issue by bespokecomponents** [cryinkfly/Fusion-360---Linux-Wine-Version-#59]
Please can you explain for to get past this after running your script in Ubuntu 18.04.5 LTS?

```
The following packages have unmet dependencies:
 winehq-staging : Depends: wine-staging (= 6.14~bullseye-1)
E: Unable to correct problems, you have held broken packages.

```

**Comment by cryinkfly** [comment]
I check this for you. :+1: 

![Bildschirmfoto_2021-08-13_09-24-37](https://user-images.githubusercontent.com/79079633/129320212-254bcf8c-c02f-4c7b-9d3a-441a42fc5d52.png)

**Comment by cryinkfly** [comment]
Okay I get the same error:

![Bildschirmfoto_2021-08-13_09-37-27](https://user-images.githubusercontent.com/79079633/129321714-a0d58b84-ebb9-4e25-85f8-82819fad3d9f.png)

**Comment by cryinkfly** [comment]
@bespokecomponents So I have found a solution!!! ^^

![Bildschirmfoto_2021-08-13_10-08-56](https://user-images.githubusercontent.com/79079633/129325616-95c903a6-0669-4871-95ff-514335904239.png)

I will change my installation-script in the next time!
