### ISSUE TITLE
Some Chinese fonts still missing.

### ISSUE THREAD

**Issue by Blue-Beaker** [cryinkfly/Fusion-360---Linux-Wine-Version-#60]
Some Chinese fonts still missing, causing Chinese filenames in the sidebar shown as rectangles.
Some other languages may have the same problem, such as Korean and Japanese.
![Screenshot_20210813_173204](https://user-images.githubusercontent.com/17115547/129336958-3b1a91de-cbfc-423f-a6df-eb799fa28e84.png)

**Comment by cryinkfly** [comment]
@Blue-Beaker Thank you very much for this report. This is the first time I see this issue. 😲

**Comment by cryinkfly** [comment]
Maybe, this helps you: https://askubuntu.com/a/1019572

**Comment by cryinkfly** [comment]
# I work on a solution!

![Bildschirmfoto_2021-08-16_19-52-51](https://user-images.githubusercontent.com/79079633/129607850-dfff8a27-5902-48ef-b83d-82926b597856.png)

**Comment by cryinkfly** [comment]
# I have solved this problem. :+1: 

What we need is "cjkfonts" and this one we must install with winetricks!!!

I change my installation-script! 

https://user-images.githubusercontent.com/79079633/129611949-fa601460-3b0b-449d-8dbe-ebada813f899.mp4
