### ISSUE TITLE
7zip "Failed to load Config" issues on Arch Linux *solved*

### ISSUE THREAD

**Issue by danieldides** [cryinkfly/Fusion-360---Linux-Wine-Version-#61]
Hello! Thanks so much for putting this script together and supporting it as you are. I'd love to get it working on my machine but I'm having some issues.

I'm running Arch Linux, fully updated. The script seems to run through but fails after downloading the Fusion installer. Eventually, it fails and a Wine window titled "7-Zip" pops open with the text saying "Can't load config info." 

In the logs, I see lots of messages saying:
> "wine: couldn't open directory L"unix\\home\\.wineprefix\\fusion360...", starting in the Windows directory.

I've tried running this with a different, downgraded version of Wine and the error went away, but it errors out later. 

Let me know if you have any ideas!

![2021-08-14-185132_1920x1080_scrot](https://user-images.githubusercontent.com/8784265/129463228-ce13cbbe-1b2f-49ae-b2eb-a1c47511d7fa.png)

> daniel@archbook ~ $ wine --version
> wine-6.15
> daniel@archbook ~ $ winetricks --version
> 20210206 - sha256sum: fca9fc58fa48951cecf67b8d42aa6b947f90307a08415d9403d2b8913e03a1d7

**Comment by cryinkfly** [comment]
Can you please download my script again, because I have revised it again! 😊

**Comment by nyakokitsu** [comment]
@cryinkfly actual for installer now
