### ISSUE TITLE
x-gnome crashes after machine is almost completlly booted up

### ISSUE THREAD

**Issue by Glasses8448** [cryinkfly/Fusion-360---Linux-Wine-Version-#62]
Since the first reboot after executing the script (everyting went fine, fusion360 was running fine), I have trouble starting my system. 

The system boots up quite normaly, I see my usual Desktop about two seconds and than the desktop enviroment crashes, blank screen about one second, and than it promted me this terminal like screen.
On the first boot, the last line of it was: *nvidia persistence daemon* but now it changed to:started *Gnome Display Manager*
And it seems that it is to related to X-gnome or nvidia.

To encounter the problem I removed the *~/config* and rebooted. Everything was fine again, but after the next boot the problem consists again.

Is there anything in your skript, that changes something related to x-gnome or nvidia?

My machine is pretty much unuseable in this state :-/

normal Desktop (about 2sec)
![1](https://user-images.githubusercontent.com/53970121/129615351-07e47365-299c-4a69-a01b-a7fb947dcf5f.jpg)
than blank screen (1sec)
![2](https://user-images.githubusercontent.com/53970121/129615362-de3018cc-ed3e-41ef-86e8-1bf9dd80ae8f.jpg)
terminal like prompt. And than nothing else happends
![3](https://user-images.githubusercontent.com/53970121/129615359-b8d6a0d7-ea0b-43d9-99c9-e79d80012c42.jpg)

**Comment by Glasses8448** [comment]
Pop!_OS 21.04.
gnome 3.38.5
GeForce GTX 1050Ti

**Comment by cryinkfly** [comment]
@Glasses8448 Hey 👋, my script updates your system with your sets of repositories and then the Wine-Repository is added and all packages are needed, such as wine installed. 

Maybe by updating certain packets are not compatible with each other. 💤

Can you please send me your log file from the boot process? 🙂

This file can be found at this path:

 > /var/log/boot.log

**Comment by Glasses8448** [comment]
I solved the problem by reconfigurating my system. It seems that the error was on my side and your skript wasnt involved in it at all. Thanks for your response and the effort, you have invensted in this skript.
