### ISSUE TITLE
Font Size to tiny - 4K screen

### ISSUE THREAD

**Issue by Evanlec** [cryinkfly/Fusion-360---Linux-Wine-Version-#63]
The fonts are awfully tiny for me, making it very difficult to use.

I've tried increasing the font DPI setting via `winecfg` and also tried enabling the HighDPIScaling preview feature within Fusion360, but to no avail (all fonts are still tiny):

```
env WINEPREFIX="/home/evan/.fusion360" winecfg
```
![image](https://user-images.githubusercontent.com/10586/130030842-3299134d-0c38-433d-9871-1093381c4bd2.png)

![image](https://user-images.githubusercontent.com/10586/130030922-acfee0f0-d0e0-470a-bfb6-b589564b4a65.png)

I'm using a 4K screen (3840x2160) so I can understand why the fonts are small out-of-the-box, but if anyone knows how to make them more _readable_ (i.e. **bigger**), I'd appreciate it!

**Comment by cryinkfly** [comment]
@Evanlec Can you testing Autodesk Fusion 360 again with this option:

![A821B2D9-662E-403B-8B3C-4BDD5D3E2269](https://user-images.githubusercontent.com/79079633/130267383-0c66efc8-b29f-4c6c-b981-c00d553e4fdd.jpeg)

**Comment by MrEdd123** [comment]
Hallo Evanlec,
i have the same Problem.
You must change the resolution in wine user.reg to your Monitorresolution. 

https://askubuntu.com/questions/1035000/change-resolution-in-wineconfig

**Comment by cosmicaug** [comment]
I am having this issue. Previous post has not been helpful to me. I'm on Mint 20.3 with Cinnamon desktop.

**Comment by baranyibence** [comment]
I had this issue too. I solved it by running the winecfg from inside the wineprefixes/default folder, like this

env WINEPREFIX="/home/bence/.fusion360/wineprefixes/default" winecfg
