### ISSUE TITLE
some elements seems detached from the main window

### ISSUE THREAD

**Issue by moham96** [cryinkfly/Fusion-360---Linux-Wine-Version-#65]
Is this really working for everyone else?
first try for me the program would install but would not login, after cleaning the wineprefix and starting again, i can now login and open the programs but it's unstable. if i minimize and then maximize the window then it wouldn't draw quickly, if i maximize the window and then open up a new window of another program then some of the elements of the Fusion 360 window would appear overlaying the second window.
expanding all the objects in the left browser casues the objects to draw on each other and thus not being able to edit or select anything.
![fusion](https://user-images.githubusercontent.com/10559702/130510166-bf91e07d-50d8-4081-9aef-38a92ef5440f.png)

![fusion360](https://user-images.githubusercontent.com/10559702/130509777-a58d3157-3873-4fb1-ad8a-4ceff6cea97e.png)

**Comment by cryinkfly** [comment]
@moham96 Hey 👋🏻,

this issue is already opened here: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/9
