### ISSUE TITLE
Selecting some objects with left click does not highlight them

### ISSUE THREAD

**Issue by blazej222** [cryinkfly/Fusion-360---Linux-Wine-Version-#66]
I'm using laptop with 2 Graphics Cards - Nvidia and Intel. OS is Archlinux, drivers are nouveau and mesa. When hovering over face of an object it changes color from grey to slightly brighter grey, but after left clicking face its color is indistinguishable from non-clicked variant. The object is selected, because I can freely move it and change its attributes, but it is not highlighted in blue as it would be in Windows. The same applies to lines in sketches - after left clicking them, they won't become highlighted, but program selects them properly. 

Attaching photos below:
 Sketch line not selected:
![line_not_selected](https://user-images.githubusercontent.com/38702081/130769546-2777b12b-4dce-43f6-a211-797d742dbd25.png)

Sketch line selected:
![line_selected](https://user-images.githubusercontent.com/38702081/130769588-0529fb43-5da9-4df1-b440-9601bced77fe.png)

Object face hovered over:
![face_hover](https://user-images.githubusercontent.com/38702081/130769693-89cabdf1-b5ba-42db-a251-511c2df71892.png)

Object face clicked:
![face_clicked](https://user-images.githubusercontent.com/38702081/130769716-2dd75e44-6994-47a8-b928-01aed51888b8.png)

Object face not selected:
![Face_not_selected](https://user-images.githubusercontent.com/38702081/130769738-040240b0-c081-4aa4-9296-d6140c863b60.png)

Surprisingly, it works on some things (circular faces):
![working_example](https://user-images.githubusercontent.com/38702081/130770256-f06c472e-33ab-4fb3-8c0f-960fe595b44f.png)

No errors show up in terminal when clicking objects. On windows after clicking objects they turn slightly blue.Also, when selecting operations in timeline, bodies created by those operations won't highlight.

Edit:
After some digging, I can confirm the problem does not occur when switching OpenGL to DirectX9. However, after changing window size on DX9 the toolbar becomes unreadable(full of artifacts instead of icons)

**Comment by cryinkfly** [comment]
@blazej222 Thank you very much for this information. I'll take a look at it later.

**Comment by TN-1** [comment]
I can confirm this issue. Ubuntu 21.04 with Intel HD 620, driver is:  
/lib/modules/5.11.0-31-generic/kernel/drivers/gpu/drm/i915/i915.ko

**Comment by blazej222** [comment]
I've tested multiple configurations, and this problem occurs only on Intel GPU and only with OpenGL as renderer - after switching to DX9 I was able to run Fusion without any issues (I fixed crashes on DX9 with Intel GPU by removing `xf86-video-intel` and other `xf86-` related packages, btw. those cause a lot of problems with Fusion so use modesetting driver instead if you encounter any issues).

My card is also Intel HD 620.
So, looks like it has something to do with Intel OpenGL implementation?

**Comment by blazej222** [comment]
Ok, did some more testing and was able to reproduce this issue on Nvidia card (with DRI_PRIME=1) on `nouveau` drivers. Same case as Intel GPU, no highlighting on OpenGL renderer, works perfectly fine on DX9 renderer.

`glxinfo -B` on `nouveau`:
```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: nouveau (0x10de)
    Device: NV118 (0x134d)
    Version: 21.2.1
    Accelerated: yes
    Video memory: 2047MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.3
    Max compat profile version: 4.3
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: nouveau
OpenGL renderer string: NV118
OpenGL core profile version string: 4.3 (Core Profile) Mesa 21.2.1
OpenGL core profile shading language version string: 4.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.3 (Compatibility Profile) Mesa 21.2.1
OpenGL shading language version string: 4.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

`glxinfo -B` on Intel:

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 620 (KBL GT2) (0x5916)
    Version: 21.2.1
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.1
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.1
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

```

Both use Mesa OpenGL, so that could be the problem.

**Comment by TN-1** [comment]
I was able to fix this by using DXVK and DX9. See #78
