### ISSUE TITLE
Fusion 360 not working on Ubuntu 20.04 with Quadro P2000-GPU

### ISSUE THREAD

**Issue by brano1990** [cryinkfly/Fusion-360---Linux-Wine-Version-#67]
hello not working properly

The cloud works but does not display the drawing

I use the version on windows free

it doesn't work on lunux

![Snímka obrazovky z 2021-08-27 08-30-19](https://user-images.githubusercontent.com/59432151/131082814-4d5f0919-f085-410b-ae55-0281a6c40e42.png)

**Comment by cryinkfly** [comment]
@brano1990 Can you tell me more about your repository's and if you have installed the newest NVIDIA graphics card drivers.

**Comment by cryinkfly** [comment]
Please check this one: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/30#issuecomment-911928607
