### ISSUE TITLE
Program Launcher - Standard Installation *solved*

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Fusion-360---Linux-Wine-Version-#70]
1. Download my [Program Launcher - Standard Installation](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/raw/main/files/Autodesk%20Fusion%20360.desktop)
2. Change to this path:

         /home/steve/.local/share/applications/

3. Save there my file "Autodesk Fusion 360.desktop"

**Comment by JamesNewton** [comment]
The link above for " Program Launcher - Standard Installation" is a 404
