### ISSUE TITLE
New launcher maybe do not run newest version. *solved*

### ISSUE THREAD

**Issue by Tony763** [cryinkfly/Fusion-360---Linux-Wine-Version-#71]
Hi @cryinkfly, I am not 100% sure but i think when Fusion get (bigger) update, directory name is changed.

New launcher presented in  PR #70 uses:

`find /$HOME -name Fusion360.exe -printf %h -quit 2>/dev/null`
and for me it return:
`//home/tony/aplications/fusion360/drive_c/Program Files/Autodesk/webdeploy/production/e69ac0f55aa8512db83c718906bbdedf0daa2f89`

But that's not latest version, correct is '4c84784f9b312b4c6ccb78d46529ebb70d7a5a09\:
```
ls -la /home/tony/aplications/fusion360/drive_c/Program\ Files/Autodesk/webdeploy/production/
celkem 72

drwxrwxr-x 46 tony tony 20480 jun 19 20:33 e69ac0f55aa8512db83c718906bbdedf0daa2f89
drwxrwxr-x 45 tony tony 20480 jul 28 22:54 4c84784f9b312b4c6ccb78d46529ebb70d7a5a09
drwxrwxr-x  2 tony tony  4096 jul 24 12:46 6a0c9611291d45bb9226980209917c3d
drwxrwxr-x 46 tony tony 20480 jun 16 19:23 9b196c6eb71126665f61dbf5a4b48d188eb6263c
```

Something like this would return latest created file:
`find /$HOME -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/'`

**Comment by cryinkfly** [comment]
Hey @Tony763 I already noticed that in advance ... 😅

But since I'm actually still on vacation, I haven't checked that when a newer version comes out. 🤔😊

Thank you again for your great help! 👌

**Comment by cryinkfly** [comment]
So I was able to incorporate your idea and created a solution:

    fusion360starter="$(find $HOME -name Fusion360.exe -printf "%T+ %p\n" | sort -r 2>&1 | head -n 1 | sed -r 's/.+0000000000 (.+)/\1/')" && WINEPREFIX="$HOME/.wineprefixes/fusion360" wine "$fusion360starter"
