### ISSUE TITLE
pzip-full and pzip-rar not available for Manjaro *solved*

### ISSUE THREAD

**Issue by tomlawesome** [cryinkfly/Fusion-360---Linux-Wine-Version-#74]
I noticed it mentioned Manjaro is compatible, but I can't find two of the required packages even in the AUR repo. 

- pzip-full
- pzip-rar

Mentions Manjaro/Arch support here: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-#hardware-and-software-requirements

________________________

![image](https://user-images.githubusercontent.com/76453276/131878161-c2f5b040-62d1-42c3-b6a4-684cb2410800.png)

**Comment by blazej222** [comment]
Hi, in ArchLinux/Manjaro this is just one single package called `p7zip`. You can see the packages installed in install script:
`function archlinux_2 {
   sudo pacman -Sy --needed wine wine-mono wine_gecko winetricks p7zip curl cabextract samba ppp
}`
I believe `p7zip` is split into multiple packages in other distros, hence those names are present in "requirements".
Do you have any problems with running the script?

**Comment by cryinkfly** [comment]
@tomlawesome The packages you see in the picture are just a brief overview. :+1:

**Comment by tomlawesome** [comment]
> Hi, in ArchLinux/Manjaro this is just one single package called `p7zip`. You can see the packages installed in install script:
> 
> ```
> function archlinux_2 {
>    sudo pacman -Sy --needed wine wine-mono wine_gecko winetricks p7zip curl cabextract samba ppp
> }
> ```
> 
> I believe `p7zip` is split into multiple packages in other distros, hence those names are present in "requirements".
> Do you have any problems with running the script?

Yes, unfortunately neither script works. 

Flatpak script fails too (I appreciate this is experimental):

```
error: Nothing matches org.winehq.flatpak-proton-68-ge-1 in remote flathub
error: app/org.winehq.flatpak-proton-68-ge-1/x86_64/master not installed
error: app/org.winehq.flatpak-proton-68-ge-1/x86_64/master not installed
```

**Comment by blazej222** [comment]
> Yes, unfortunately neither script works.
What message does the main (not flatpak) script fail with?

**Comment by tomlawesome** [comment]
> > Yes, unfortunately neither script works.
> 
> What message does the main (not flatpak) script fail with?

Just running it again now, it spams this warning constantly throughout running the script:

```
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

```

**Comment by blazej222** [comment]
Ok, have you tried running the app after closing installation? You didn't have error *before* installation finished, so I suppose you might try running the app? 

Please run it via this command (replacing paths if necessary)
```
F360DIR="$HOME/.wineprefixes/fusion360/"
env WINEPREFIX="${F360DIR}" wine C:\\windows\\command\\start.exe /Unix "${F360DIR}/drive_c/ProgramData/Microsoft/Windows/Start Menu/Programs/Autodesk/Autodesk Fusion 360.lnk"
```
If you encounter any errors, paste them here.

Sometimes wine just throws out random errors without any real reason.

**Comment by cryinkfly** [comment]
@blazej222 and @tomlawesome Check this new program launcher: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/70

Then I have implemented this in my installation script! ✅
