### ISSUE TITLE
DXVK & DX9/11

### ISSUE THREAD

**Issue by TN-1** [cryinkfly/Fusion-360---Linux-Wine-Version-#78]
Installed DXVK through winetricks, and selected DX9/11 in the Fusion 360 graphical settings.  
Startup and the base UI seems to be better behaved than using OpenGL (Toolbars dont stay on top, general performance seems better), however the main screen is borked.
![Screenshot from 2021-09-03 17-30-34](https://user-images.githubusercontent.com/11869589/131971887-0cc18fda-e206-4fa1-8bc7-6587c7a3137f.png)

**Comment by cryinkfly** [comment]
## When you will use DXVK then you must change these things:

- d3d10core = disabled
- d3d11 = native
- d3d9 = builtin
- dxgi = native

... and then you must selected DX9 in the Fusion 360 graphical settings and restart the program!

![Bildschirmfoto_2021-09-03_10-14-04](https://user-images.githubusercontent.com/79079633/131973483-8739d680-189c-4f35-8ff1-67e7339892f5.png)

**Comment by TN-1** [comment]
Thats got it working, and from a very quick mess around has greatly improved performance. Thankyou!

**Comment by cryinkfly** [comment]
That was in my manual at the time and had taken it out because Autodesk had then published the OpenGL variant and for some users it worked better than the dxvk variant. ⚙️

But I will include it in detail in the documentation. 😊

**Comment by cryinkfly** [comment]
I have published a manual: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/79
