### ISSUE TITLE
Activate DXVK and use DirectX 9 *solved*

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Fusion-360---Linux-Wine-Version-#79]
Would you like to use Autodesk Fusion 360 with DirectX 9 instead of OpenGL?

Then you have to work through the following steps:

**1) Install the package "dxvk" with the help of winetricks!** Example command:

       WINEPREFIX=/home/$USER/.wineprefixes/fusion360 sh winetricks -q dxvk

**2a) Autodesk Fusion 360 has already started:**

> Then go to preferences and in General under Graphics driver select DirectX 9.
> After this setting, Exit Autodesk Fusion 360.

**2b) Autodesk Fusion 360 was configured by you after the installation:**

> Download this file: [NMachineSpecificOptions.xml.zip](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/7105337/NMachineSpecificOptions.xml.zip)
> Then you have to replace the original NMachineSpecificOptions.xml file that you received with the installation of Autodesk Fusion 360 with this file!
> Here you can find this original file if you have selected the "Standard Installation": 

- /$HOME/.wineprefixes/fusion360/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform/Options
- /$HOME/.wineprefixes/fusion360/drive_c/users/$USER/AppData/Roaming/Autodesk/Neutron Platform/Options

**3) After that you must change your Wine configuration:**

       WINEPREFIX=/home/$USER/.wineprefixes/fusion360 winecfg

> Then you go to libraries and change these things:

- d3d10core = disabled
- d3d11 = native
- d3d9 = builtin
- dxgi = native

**4) You can now start Autodesk Fusion 360!**

**Comment by ManuGithubSteam** [comment]
What is the benefit of running it with DirectX 9  ? will the GUI glitches be gone ?
Thanks!

**Comment by TN-1** [comment]
@ManuGithubSteam Some users report a better experience, including me. Other people have a better experience on OpenGL. It's just a matter of seeing what works best for your setup.
