### ISSUE TITLE
How to apply OpenGL setting before 1st launch

### ISSUE THREAD

**Issue by dreamcat4** [cryinkfly/Fusion-360---Linux-Wine-Version-#8]
Hey again @cryinkfly 
I noticed that you tried to append an `-opengl` cmdline flag to the wine command, or to windows shortcut `.lnk`. However that did not work for me.

So yesterday Beyond Compare to folder diff the whole C drive. After changing the OpenGL option in preferences. And found out how to do this.

Here the linux commands, to just copy-paste into your linux terminal. This will create initial settings file on disk, before doing 1st launch, 1st login. We can already set the opengl graphics mode.

```sh
mkdir -p "$WINEPREFIX/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform/Options"
cat > "$WINEPREFIX/drive_c/users/$USER/Application Data/Autodesk/Neutron Platform/Options/NMachineSpecificOptions.xml" << "E"
<?xml version="1.0" encoding="UTF-16" standalone="no" ?>
<OptionGroups>
  <BootstrapOptionsGroup SchemaVersion="2" ToolTip="Special preferences that require the application to be restarted after a change." UserName="Bootstrap">
    <driverOptionId ToolTip="The driver used to display the graphics" UserName="Graphics driver" Value="VirtualDeviceGLCore"/></BootstrapOptionsGroup>
</OptionGroups>
E

```

so long as the `$WINEPREFIX` environment variable is set, and the `$USER` is not using sudo. Then wine and fusion predictably always use the same file location.

I have tested it this morning from a clean install. And without ever installing `dxvk` (at all). So then the before command for winetricks (minimum dependancies) is...

```sh
winetricks corefonts vcrun2017 msxml4
```

And also, with no dxvk whatsoever... then step 

19.) Run this command: winecfg -> Go to libraries -> Change these options:

```sh
d3d10core = disabled
d3d11 = builtin
d3d9 = builtin
dxgi = builtin
```

is not needed anymore either.

I do not know what is the difference for performance. Because my graphics is GT1030, which is rather too slow to notice faster or slower. But it seems the same?

Also I still have the other bug here, without any dxvk the floating browser menus, always ontop in foreground.

**Comment by cryinkfly** [comment]
@dreamcat4 Have I now understood correctly that it works on your system?

... when you have installed: 

> winetricks winetricks corefonts vcrun2017 msxml4

**Comment by dreamcat4** [comment]
it works too with your latest ammeded instructions. however if you don't need to install dxvk at all (for opengl mode)... then it saves certain extra steps. and having to reboot fusion360 multiple times. or launch other gui stuff

so the only remaining 'interactive' steps is installing the microsoft .net frameworks, and the microsoft msxml library. which unfortunately IDK / cannot think of a good solution for

**Comment by cryinkfly** [comment]
@dreamcat4 Can you give me a step by step manual of your way again, so I can test this with my Flatpak version of Fusion 360 😊

**Comment by dreamcat4** [comment]
sure!
i shall be working on that during today. it is mostly the same as your instruction for ubuntu 20.04 / mint. just with a few of the steps changed

And i shall open a new issue for discussing the other graphics bug

**Comment by cryinkfly** [comment]
Okay. Thank you very much!

**Comment by cryinkfly** [comment]
For all users, please also check out this issue: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/58
