### ISSUE TITLE
Install script error *solved*

### ISSUE THREAD

**Issue by apopticon** [cryinkfly/Fusion-360---Linux-Wine-Version-#81]
Line 133 of the script - select-dxvk-or-opengl is misspelled and the script dies with not found error.

**Comment by pulponair** [comment]
@apopticon confirmed. but you can just correct it :)

**Comment by apopticon** [comment]
I did!

**Comment by pulponair** [comment]
funny that you run in exact the same issue 3 minutes before me :)

**Comment by apopticon** [comment]
Just lucky I guess...

**Comment by apopticon** [comment]
The script calls select_dxvk_or_opengl but the correct function name is select-dxvk-or-opengl

**Comment by cryinkfly** [comment]
@apopticon Thank you for your help. 😊
