### ISSUE TITLE
Install script error

### ISSUE THREAD

**Issue by apopticon** [cryinkfly/Fusion-360---Linux-Wine-Version-#83]
Install script dies at line 623: logfile-installation-standard: command not found

**Comment by apopticon** [comment]
There are functions for logfile-installation  and logfile-installation-custom, but that's it.

**Comment by apopticon** [comment]
I'm guessing that logfile-installation-standard should actually have been logfile-installation

**Comment by cryinkfly** [comment]
@apopticon Have I already changed it or have I overlooked something? 😅😊

**Comment by apopticon** [comment]
This is a second issue, I might have used the same subject though. The script calls logfile-installation-standard, if you change it to call logfile-installation then all is well.

**Comment by cryinkfly** [comment]
https://user-images.githubusercontent.com/79079633/132102007-0c54a8f5-571b-44a4-a0de-29beb7e6560e.mp4

**Comment by apopticon** [comment]
I must somehow have a version that's out of sync then...  I have now confirmed that https://raw.githubusercontent.com/cryinkfly/Fusion-360---Linux-Wine-Version-/main/scripts/stable-branch/fusion360-install.sh does reflect the proper function name.  ¯\_(ツ)_/¯
