### ISSUE TITLE
issue installing on Mint 20.2 under a VMWare machine

### ISSUE THREAD

**Issue by DJSpray** [cryinkfly/Fusion-360---Linux-Wine-Version-#84]
Hi and thanks for your amazing work.
I currently run under windows 10 and the only program left not working under linux is Fusion360.
I've been looking at various tutorials (playonlinux, lutris.....) but none seem to work and now I get on your solution that is just amazing in terms of work and package solution! bravo!

still, it does not work on my fresh installed VM. (double click shows working mouse icon for a few seconds then nothing... even after hours of wait). My computer is a Lenovo X1Carbon, equipped with a i7 processor and 16GB Ram. VM has two cores and 8GB ram assigned.
Is it because I run a virtual machine and not a physical computer? am I missing something?

if you can give this a try (just install a Mint on VMWare and run your script) to tell me what is causing this, that would be so awesome.
Sorry for daring asking you so much, hope you can help me!

Regards,

Allan.

**Comment by cryinkfly** [comment]
@DJSpray You are welcome. 😊

I'll take a look at it. 👍

I just had to change my script before I have seen your post because I had forgotten something in two places due to the restructuring of the scropted. 😅

**Comment by cryinkfly** [comment]
I have tested this into a VM and it works perfectly for me! 👍

![Bildschirmfoto_2021-09-04_19-34-25](https://user-images.githubusercontent.com/79079633/132103487-999728f0-8d56-4033-8a0c-e2d177a15d63.png)

**Comment by DJSpray** [comment]
Damn.....
I have to see why it does so, but at least I know it should :)

Will try again and keep you posted.

**Comment by cryinkfly** [comment]
Okay 👍 I will temporarily close this post.

If the problem persists, please re-open this post again here! 😊

**Comment by DJSpray** [comment]
Hi Cryinkfly.
just for info, I was tired of trying on VMWare and installed VirtualBox to
give it a try.
worked from the first try!
thanks and sorry again!

Le sam. 4 sept. 2021 à 20:59, Steve Zabka ***@***.***> a
écrit :
