### ISSUE TITLE
Arch Linux (KDE Plasma on Wayland) - Installer crashes after installing dialog and wmctrl

### ISSUE THREAD

**Issue by Lava3063** [cryinkfly/Fusion-360---Linux-Wine-Version-#87]
It just kicks me out. Packages are installed, as it says warning: package is up to date -- skipping.

Using Arch Linux and KDE Plasma on wayland.

**Comment by cryinkfly** [comment]
@Lava3063 Can you read this post here: https://bbs.archlinux.org/viewtopic.php?id=240397 :+1:

**Comment by Lava3063** [comment]
It already has --needed in it. Tried removing it, and it still failed. Try adding --noconfirm, and it still stopped.

**Comment by blazej222** [comment]
Please replace the bottom part of the script with this code:
```
##############################################################################
# THE INSTALLATION PROGRAM IS STARTED HERE:
##############################################################################
exec 5> log.txt
BASH_XTRACEFD="5"
set -x
clear &&
select-language &&
check-requirement

############################################################################################################################################################
```
And attach resulting `log.txt` file here.

**Comment by cryinkfly** [comment]
@blazej222 Thank you for this information! I've looked at it and will build it into it. 

> https://unix.stackexchange.com/questions/155551/how-to-debug-a-bash-script

**Comment by blazej222** [comment]
> @blazej222 Thank you for this information! I've looked at it and will build it into it. 

I've already included it in my upcoming commits, but haven't created pull request yet (still working on some minor tweaks)

> But the problem is that we can't see the processes!!! We can only see the steps of the installation (commands).

Yes, but we can possibly find where it fails (on which function call). I think it would be a good place to start debugging :smiley:

**Comment by cryinkfly** [comment]
@blazej222 We can also discuss these special things here in the future: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/discussions :smiley:

**Comment by Lava3063** [comment]
Reinstalled system after a makepkg issue, and now it suddenly works. No idea what caused it to error last time. Marking as closed.
