### ISSUE TITLE
Script bug -- typos in fedora installation functions *solved*

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [cryinkfly/Fusion-360---Linux-Wine-Version-#88]
Hi!

Fantastic solution you have developed.  Thanks so much for your contribution to the community.

Note that you have a small naming typo in the fedora installation methods on lines 512 and 518.  You've used underscores to name the functions, but call them with hyphens.  Renaming the functions results in a perfect install.

**Comment by cryinkfly** [comment]
@ThisIsTheOnlyUsernameAvailable Thank you for this report! ✅ I have changed these lines. 👍
