### ISSUE TITLE
Script terminate after installing/checking for "dialog" & "wmctrl" packages

### ISSUE THREAD

**Issue by syfq91** [cryinkfly/Fusion-360---Linux-Wine-Version-#92]
Re-run the script does not help, it still stops at the same place.

Below is the terminal output:

```
In this step, the following packages package >dialog< and >wmctrl< are installed for the installation of Autodesk Fusion 360!
Do you wish to install these packages (y/n)?y
Debian-based
Hit:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 http://security.ubuntu.com/ubuntu hirsute-security InRelease
Hit:3 http://my.archive.ubuntu.com/ubuntu hirsute InRelease
Hit:4 http://my.archive.ubuntu.com/ubuntu hirsute-updates InRelease
Hit:5 http://my.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
software-properties-common is already the newest version (0.99.10).
dialog is already the newest version (1.3-20201126-1).
wmctrl is already the newest version (1.07-7build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
user@hppc:~/Downloads$ 
```

Any idea how to proceed?

OS version: Ubuntu 21.04 64-bit
Windowing system: Wayland

**Comment by cryinkfly** [comment]
Hey @syfq91 🙂 I think you have the same issue like this one: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/87 

But the only thing is that this user use Arch Linux. 😉

**Comment by TN-1** [comment]
I believe I have identified and fixed this issue. I have created a PR to fix. @syfq91 Please try again with the fix list in the PR.  
Simple typo, missing a &&

**Comment by TN-1** [comment]
> Hey @syfq91  I think you have the same issue like this one: #87
> 
> But the only thing is that this user use Arch Linux.

If my PR fixes this issue, then that will be a different bug. This should only affect Ubuntu 21.04 users.

**Comment by TN-1** [comment]
Ok I have tracked this issue down properly and confirmed the fix. It is contained in #94  
I don't know why this extra echo fixes the script, but I had it in there for a debug message and it solved it. Technology amiright?

**Comment by syfq91** [comment]
Thank you everyone for the help. I can confirm that adding echo fixed this issue. It is installing now.
